
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  TechSkill: 'TechSkill',
  ProjectImages: 'ProjectImages',
  Project: 'Project',
  Ingredient: 'Ingredient',
  MealPrep: 'MealPrep'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const TechSkillScalarFieldEnum = {
  id: 'id',
  local_rel: 'local_rel',
  label: 'label',
  dest: 'dest',
  category: 'category',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TechSkillScalarFieldEnum = (typeof TechSkillScalarFieldEnum)[keyof typeof TechSkillScalarFieldEnum]


export const ProjectImagesScalarFieldEnum = {
  id: 'id',
  screenshots: 'screenshots',
  thumb: 'thumb',
  project_id: 'project_id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectImagesScalarFieldEnum = (typeof ProjectImagesScalarFieldEnum)[keyof typeof ProjectImagesScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  short_desc: 'short_desc',
  long_desc: 'long_desc',
  overview_desc: 'overview_desc',
  architecture_desc: 'architecture_desc',
  practiced_skills_desc: 'practiced_skills_desc',
  goal_desc: 'goal_desc',
  project_phase: 'project_phase',
  video_preview: 'video_preview',
  github_url: 'github_url',
  website_url: 'website_url',
  docs_url: 'docs_url',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const IngredientScalarFieldEnum = {
  id: 'id',
  label: 'label',
  unit: 'unit',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type IngredientScalarFieldEnum = (typeof IngredientScalarFieldEnum)[keyof typeof IngredientScalarFieldEnum]


export const MealPrepScalarFieldEnum = {
  id: 'id',
  name: 'name',
  coverage: 'coverage',
  images: 'images',
  cookedAt: 'cookedAt',
  updatedAt: 'updatedAt'
} as const

export type MealPrepScalarFieldEnum = (typeof MealPrepScalarFieldEnum)[keyof typeof MealPrepScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

