
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Project` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Project
 * 
 */
export type ProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjectPayload>

export type AggregateProject = {
  _count: ProjectCountAggregateOutputType | null
  _min: ProjectMinAggregateOutputType | null
  _max: ProjectMaxAggregateOutputType | null
}

export type ProjectMinAggregateOutputType = {
  id: string | null
  name: string | null
  short_desc: string | null
  long_desc: string | null
  overview_desc: string | null
  architecture_desc: string | null
  practiced_skills_desc: string | null
  goal_desc: string | null
  project_phase: string | null
  video_preview: string | null
  github_url: string | null
  website_url: string | null
  website_logo_url: string | null
  docs_url: string | null
  project_type: $Enums.ProjectType | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectMaxAggregateOutputType = {
  id: string | null
  name: string | null
  short_desc: string | null
  long_desc: string | null
  overview_desc: string | null
  architecture_desc: string | null
  practiced_skills_desc: string | null
  goal_desc: string | null
  project_phase: string | null
  video_preview: string | null
  github_url: string | null
  website_url: string | null
  website_logo_url: string | null
  docs_url: string | null
  project_type: $Enums.ProjectType | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectCountAggregateOutputType = {
  id: number
  name: number
  short_desc: number
  long_desc: number
  overview_desc: number
  architecture_desc: number
  practiced_skills_desc: number
  goal_desc: number
  project_phase: number
  video_preview: number
  github_url: number
  website_url: number
  website_logo_url: number
  docs_url: number
  project_type: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProjectMinAggregateInputType = {
  id?: true
  name?: true
  short_desc?: true
  long_desc?: true
  overview_desc?: true
  architecture_desc?: true
  practiced_skills_desc?: true
  goal_desc?: true
  project_phase?: true
  video_preview?: true
  github_url?: true
  website_url?: true
  website_logo_url?: true
  docs_url?: true
  project_type?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectMaxAggregateInputType = {
  id?: true
  name?: true
  short_desc?: true
  long_desc?: true
  overview_desc?: true
  architecture_desc?: true
  practiced_skills_desc?: true
  goal_desc?: true
  project_phase?: true
  video_preview?: true
  github_url?: true
  website_url?: true
  website_logo_url?: true
  docs_url?: true
  project_type?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectCountAggregateInputType = {
  id?: true
  name?: true
  short_desc?: true
  long_desc?: true
  overview_desc?: true
  architecture_desc?: true
  practiced_skills_desc?: true
  goal_desc?: true
  project_phase?: true
  video_preview?: true
  github_url?: true
  website_url?: true
  website_logo_url?: true
  docs_url?: true
  project_type?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Project to aggregate.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Projects
  **/
  _count?: true | ProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjectMaxAggregateInputType
}

export type GetProjectAggregateType<T extends ProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProject[P]>
    : Prisma.GetScalarType<T[P], AggregateProject[P]>
}




export type ProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithAggregationInput | Prisma.ProjectOrderByWithAggregationInput[]
  by: Prisma.ProjectScalarFieldEnum[] | Prisma.ProjectScalarFieldEnum
  having?: Prisma.ProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjectCountAggregateInputType | true
  _min?: ProjectMinAggregateInputType
  _max?: ProjectMaxAggregateInputType
}

export type ProjectGroupByOutputType = {
  id: string
  name: string
  short_desc: string
  long_desc: string
  overview_desc: string
  architecture_desc: string
  practiced_skills_desc: string
  goal_desc: string
  project_phase: string | null
  video_preview: string | null
  github_url: string | null
  website_url: string | null
  website_logo_url: string | null
  docs_url: string | null
  project_type: $Enums.ProjectType
  createdAt: Date
  updatedAt: Date
  _count: ProjectCountAggregateOutputType | null
  _min: ProjectMinAggregateOutputType | null
  _max: ProjectMaxAggregateOutputType | null
}

type GetProjectGroupByPayload<T extends ProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjectGroupByOutputType[P]>
      }
    >
  >



export type ProjectWhereInput = {
  AND?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  OR?: Prisma.ProjectWhereInput[]
  NOT?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  id?: Prisma.StringFilter<"Project"> | string
  name?: Prisma.StringFilter<"Project"> | string
  short_desc?: Prisma.StringFilter<"Project"> | string
  long_desc?: Prisma.StringFilter<"Project"> | string
  overview_desc?: Prisma.StringFilter<"Project"> | string
  architecture_desc?: Prisma.StringFilter<"Project"> | string
  practiced_skills_desc?: Prisma.StringFilter<"Project"> | string
  goal_desc?: Prisma.StringFilter<"Project"> | string
  project_phase?: Prisma.StringNullableFilter<"Project"> | string | null
  video_preview?: Prisma.StringNullableFilter<"Project"> | string | null
  github_url?: Prisma.StringNullableFilter<"Project"> | string | null
  website_url?: Prisma.StringNullableFilter<"Project"> | string | null
  website_logo_url?: Prisma.StringNullableFilter<"Project"> | string | null
  docs_url?: Prisma.StringNullableFilter<"Project"> | string | null
  project_type?: Prisma.EnumProjectTypeFilter<"Project"> | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  images?: Prisma.XOR<Prisma.ProjectImagesNullableScalarRelationFilter, Prisma.ProjectImagesWhereInput> | null
  awards?: Prisma.ProjectAwardListRelationFilter
  skills?: Prisma.TechSkillListRelationFilter
}

export type ProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  short_desc?: Prisma.SortOrder
  long_desc?: Prisma.SortOrder
  overview_desc?: Prisma.SortOrder
  architecture_desc?: Prisma.SortOrder
  practiced_skills_desc?: Prisma.SortOrder
  goal_desc?: Prisma.SortOrder
  project_phase?: Prisma.SortOrderInput | Prisma.SortOrder
  video_preview?: Prisma.SortOrderInput | Prisma.SortOrder
  github_url?: Prisma.SortOrderInput | Prisma.SortOrder
  website_url?: Prisma.SortOrderInput | Prisma.SortOrder
  website_logo_url?: Prisma.SortOrderInput | Prisma.SortOrder
  docs_url?: Prisma.SortOrderInput | Prisma.SortOrder
  project_type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  images?: Prisma.ProjectImagesOrderByWithRelationInput
  awards?: Prisma.ProjectAwardOrderByRelationAggregateInput
  skills?: Prisma.TechSkillOrderByRelationAggregateInput
}

export type ProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  OR?: Prisma.ProjectWhereInput[]
  NOT?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  short_desc?: Prisma.StringFilter<"Project"> | string
  long_desc?: Prisma.StringFilter<"Project"> | string
  overview_desc?: Prisma.StringFilter<"Project"> | string
  architecture_desc?: Prisma.StringFilter<"Project"> | string
  practiced_skills_desc?: Prisma.StringFilter<"Project"> | string
  goal_desc?: Prisma.StringFilter<"Project"> | string
  project_phase?: Prisma.StringNullableFilter<"Project"> | string | null
  video_preview?: Prisma.StringNullableFilter<"Project"> | string | null
  github_url?: Prisma.StringNullableFilter<"Project"> | string | null
  website_url?: Prisma.StringNullableFilter<"Project"> | string | null
  website_logo_url?: Prisma.StringNullableFilter<"Project"> | string | null
  docs_url?: Prisma.StringNullableFilter<"Project"> | string | null
  project_type?: Prisma.EnumProjectTypeFilter<"Project"> | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  images?: Prisma.XOR<Prisma.ProjectImagesNullableScalarRelationFilter, Prisma.ProjectImagesWhereInput> | null
  awards?: Prisma.ProjectAwardListRelationFilter
  skills?: Prisma.TechSkillListRelationFilter
}, "id" | "name">

export type ProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  short_desc?: Prisma.SortOrder
  long_desc?: Prisma.SortOrder
  overview_desc?: Prisma.SortOrder
  architecture_desc?: Prisma.SortOrder
  practiced_skills_desc?: Prisma.SortOrder
  goal_desc?: Prisma.SortOrder
  project_phase?: Prisma.SortOrderInput | Prisma.SortOrder
  video_preview?: Prisma.SortOrderInput | Prisma.SortOrder
  github_url?: Prisma.SortOrderInput | Prisma.SortOrder
  website_url?: Prisma.SortOrderInput | Prisma.SortOrder
  website_logo_url?: Prisma.SortOrderInput | Prisma.SortOrder
  docs_url?: Prisma.SortOrderInput | Prisma.SortOrder
  project_type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProjectCountOrderByAggregateInput
  _max?: Prisma.ProjectMaxOrderByAggregateInput
  _min?: Prisma.ProjectMinOrderByAggregateInput
}

export type ProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjectScalarWhereWithAggregatesInput | Prisma.ProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjectScalarWhereWithAggregatesInput | Prisma.ProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Project"> | string
  name?: Prisma.StringWithAggregatesFilter<"Project"> | string
  short_desc?: Prisma.StringWithAggregatesFilter<"Project"> | string
  long_desc?: Prisma.StringWithAggregatesFilter<"Project"> | string
  overview_desc?: Prisma.StringWithAggregatesFilter<"Project"> | string
  architecture_desc?: Prisma.StringWithAggregatesFilter<"Project"> | string
  practiced_skills_desc?: Prisma.StringWithAggregatesFilter<"Project"> | string
  goal_desc?: Prisma.StringWithAggregatesFilter<"Project"> | string
  project_phase?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  video_preview?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  github_url?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  website_url?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  website_logo_url?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  docs_url?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  project_type?: Prisma.EnumProjectTypeWithAggregatesFilter<"Project"> | $Enums.ProjectType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Project"> | Date | string
}

export type ProjectCreateInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
  images?: Prisma.ProjectImagesCreateNestedOneWithoutProjectInput
  awards?: Prisma.ProjectAwardCreateNestedManyWithoutProjectInput
  skills?: Prisma.TechSkillCreateNestedManyWithoutProjectsInput
}

export type ProjectUncheckedCreateInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
  images?: Prisma.ProjectImagesUncheckedCreateNestedOneWithoutProjectInput
  awards?: Prisma.ProjectAwardUncheckedCreateNestedManyWithoutProjectInput
  skills?: Prisma.TechSkillUncheckedCreateNestedManyWithoutProjectsInput
}

export type ProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProjectImagesUpdateOneWithoutProjectNestedInput
  awards?: Prisma.ProjectAwardUpdateManyWithoutProjectNestedInput
  skills?: Prisma.TechSkillUpdateManyWithoutProjectsNestedInput
}

export type ProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProjectImagesUncheckedUpdateOneWithoutProjectNestedInput
  awards?: Prisma.ProjectAwardUncheckedUpdateManyWithoutProjectNestedInput
  skills?: Prisma.TechSkillUncheckedUpdateManyWithoutProjectsNestedInput
}

export type ProjectCreateManyInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectListRelationFilter = {
  every?: Prisma.ProjectWhereInput
  some?: Prisma.ProjectWhereInput
  none?: Prisma.ProjectWhereInput
}

export type ProjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProjectScalarRelationFilter = {
  is?: Prisma.ProjectWhereInput
  isNot?: Prisma.ProjectWhereInput
}

export type ProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  short_desc?: Prisma.SortOrder
  long_desc?: Prisma.SortOrder
  overview_desc?: Prisma.SortOrder
  architecture_desc?: Prisma.SortOrder
  practiced_skills_desc?: Prisma.SortOrder
  goal_desc?: Prisma.SortOrder
  project_phase?: Prisma.SortOrder
  video_preview?: Prisma.SortOrder
  github_url?: Prisma.SortOrder
  website_url?: Prisma.SortOrder
  website_logo_url?: Prisma.SortOrder
  docs_url?: Prisma.SortOrder
  project_type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  short_desc?: Prisma.SortOrder
  long_desc?: Prisma.SortOrder
  overview_desc?: Prisma.SortOrder
  architecture_desc?: Prisma.SortOrder
  practiced_skills_desc?: Prisma.SortOrder
  goal_desc?: Prisma.SortOrder
  project_phase?: Prisma.SortOrder
  video_preview?: Prisma.SortOrder
  github_url?: Prisma.SortOrder
  website_url?: Prisma.SortOrder
  website_logo_url?: Prisma.SortOrder
  docs_url?: Prisma.SortOrder
  project_type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  short_desc?: Prisma.SortOrder
  long_desc?: Prisma.SortOrder
  overview_desc?: Prisma.SortOrder
  architecture_desc?: Prisma.SortOrder
  practiced_skills_desc?: Prisma.SortOrder
  goal_desc?: Prisma.SortOrder
  project_phase?: Prisma.SortOrder
  video_preview?: Prisma.SortOrder
  github_url?: Prisma.SortOrder
  website_url?: Prisma.SortOrder
  website_logo_url?: Prisma.SortOrder
  docs_url?: Prisma.SortOrder
  project_type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectCreateNestedManyWithoutSkillsInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutSkillsInput, Prisma.ProjectUncheckedCreateWithoutSkillsInput> | Prisma.ProjectCreateWithoutSkillsInput[] | Prisma.ProjectUncheckedCreateWithoutSkillsInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutSkillsInput | Prisma.ProjectCreateOrConnectWithoutSkillsInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
}

export type ProjectUncheckedCreateNestedManyWithoutSkillsInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutSkillsInput, Prisma.ProjectUncheckedCreateWithoutSkillsInput> | Prisma.ProjectCreateWithoutSkillsInput[] | Prisma.ProjectUncheckedCreateWithoutSkillsInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutSkillsInput | Prisma.ProjectCreateOrConnectWithoutSkillsInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
}

export type ProjectUpdateManyWithoutSkillsNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutSkillsInput, Prisma.ProjectUncheckedCreateWithoutSkillsInput> | Prisma.ProjectCreateWithoutSkillsInput[] | Prisma.ProjectUncheckedCreateWithoutSkillsInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutSkillsInput | Prisma.ProjectCreateOrConnectWithoutSkillsInput[]
  upsert?: Prisma.ProjectUpsertWithWhereUniqueWithoutSkillsInput | Prisma.ProjectUpsertWithWhereUniqueWithoutSkillsInput[]
  set?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  disconnect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  delete?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  update?: Prisma.ProjectUpdateWithWhereUniqueWithoutSkillsInput | Prisma.ProjectUpdateWithWhereUniqueWithoutSkillsInput[]
  updateMany?: Prisma.ProjectUpdateManyWithWhereWithoutSkillsInput | Prisma.ProjectUpdateManyWithWhereWithoutSkillsInput[]
  deleteMany?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
}

export type ProjectUncheckedUpdateManyWithoutSkillsNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutSkillsInput, Prisma.ProjectUncheckedCreateWithoutSkillsInput> | Prisma.ProjectCreateWithoutSkillsInput[] | Prisma.ProjectUncheckedCreateWithoutSkillsInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutSkillsInput | Prisma.ProjectCreateOrConnectWithoutSkillsInput[]
  upsert?: Prisma.ProjectUpsertWithWhereUniqueWithoutSkillsInput | Prisma.ProjectUpsertWithWhereUniqueWithoutSkillsInput[]
  set?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  disconnect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  delete?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  update?: Prisma.ProjectUpdateWithWhereUniqueWithoutSkillsInput | Prisma.ProjectUpdateWithWhereUniqueWithoutSkillsInput[]
  updateMany?: Prisma.ProjectUpdateManyWithWhereWithoutSkillsInput | Prisma.ProjectUpdateManyWithWhereWithoutSkillsInput[]
  deleteMany?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
}

export type ProjectCreateNestedOneWithoutAwardsInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutAwardsInput, Prisma.ProjectUncheckedCreateWithoutAwardsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutAwardsInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutAwardsNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutAwardsInput, Prisma.ProjectUncheckedCreateWithoutAwardsInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutAwardsInput
  upsert?: Prisma.ProjectUpsertWithoutAwardsInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutAwardsInput, Prisma.ProjectUpdateWithoutAwardsInput>, Prisma.ProjectUncheckedUpdateWithoutAwardsInput>
}

export type ProjectCreateNestedOneWithoutImagesInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutImagesInput, Prisma.ProjectUncheckedCreateWithoutImagesInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutImagesInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutImagesNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutImagesInput, Prisma.ProjectUncheckedCreateWithoutImagesInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutImagesInput
  upsert?: Prisma.ProjectUpsertWithoutImagesInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutImagesInput, Prisma.ProjectUpdateWithoutImagesInput>, Prisma.ProjectUncheckedUpdateWithoutImagesInput>
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumProjectTypeFieldUpdateOperationsInput = {
  set?: $Enums.ProjectType
}

export type ProjectCreateWithoutSkillsInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
  images?: Prisma.ProjectImagesCreateNestedOneWithoutProjectInput
  awards?: Prisma.ProjectAwardCreateNestedManyWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutSkillsInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
  images?: Prisma.ProjectImagesUncheckedCreateNestedOneWithoutProjectInput
  awards?: Prisma.ProjectAwardUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutSkillsInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutSkillsInput, Prisma.ProjectUncheckedCreateWithoutSkillsInput>
}

export type ProjectUpsertWithWhereUniqueWithoutSkillsInput = {
  where: Prisma.ProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutSkillsInput, Prisma.ProjectUncheckedUpdateWithoutSkillsInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutSkillsInput, Prisma.ProjectUncheckedCreateWithoutSkillsInput>
}

export type ProjectUpdateWithWhereUniqueWithoutSkillsInput = {
  where: Prisma.ProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutSkillsInput, Prisma.ProjectUncheckedUpdateWithoutSkillsInput>
}

export type ProjectUpdateManyWithWhereWithoutSkillsInput = {
  where: Prisma.ProjectScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyWithoutSkillsInput>
}

export type ProjectScalarWhereInput = {
  AND?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
  OR?: Prisma.ProjectScalarWhereInput[]
  NOT?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
  id?: Prisma.StringFilter<"Project"> | string
  name?: Prisma.StringFilter<"Project"> | string
  short_desc?: Prisma.StringFilter<"Project"> | string
  long_desc?: Prisma.StringFilter<"Project"> | string
  overview_desc?: Prisma.StringFilter<"Project"> | string
  architecture_desc?: Prisma.StringFilter<"Project"> | string
  practiced_skills_desc?: Prisma.StringFilter<"Project"> | string
  goal_desc?: Prisma.StringFilter<"Project"> | string
  project_phase?: Prisma.StringNullableFilter<"Project"> | string | null
  video_preview?: Prisma.StringNullableFilter<"Project"> | string | null
  github_url?: Prisma.StringNullableFilter<"Project"> | string | null
  website_url?: Prisma.StringNullableFilter<"Project"> | string | null
  website_logo_url?: Prisma.StringNullableFilter<"Project"> | string | null
  docs_url?: Prisma.StringNullableFilter<"Project"> | string | null
  project_type?: Prisma.EnumProjectTypeFilter<"Project"> | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Project"> | Date | string
}

export type ProjectCreateWithoutAwardsInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
  images?: Prisma.ProjectImagesCreateNestedOneWithoutProjectInput
  skills?: Prisma.TechSkillCreateNestedManyWithoutProjectsInput
}

export type ProjectUncheckedCreateWithoutAwardsInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
  images?: Prisma.ProjectImagesUncheckedCreateNestedOneWithoutProjectInput
  skills?: Prisma.TechSkillUncheckedCreateNestedManyWithoutProjectsInput
}

export type ProjectCreateOrConnectWithoutAwardsInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutAwardsInput, Prisma.ProjectUncheckedCreateWithoutAwardsInput>
}

export type ProjectUpsertWithoutAwardsInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutAwardsInput, Prisma.ProjectUncheckedUpdateWithoutAwardsInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutAwardsInput, Prisma.ProjectUncheckedCreateWithoutAwardsInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutAwardsInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutAwardsInput, Prisma.ProjectUncheckedUpdateWithoutAwardsInput>
}

export type ProjectUpdateWithoutAwardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProjectImagesUpdateOneWithoutProjectNestedInput
  skills?: Prisma.TechSkillUpdateManyWithoutProjectsNestedInput
}

export type ProjectUncheckedUpdateWithoutAwardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProjectImagesUncheckedUpdateOneWithoutProjectNestedInput
  skills?: Prisma.TechSkillUncheckedUpdateManyWithoutProjectsNestedInput
}

export type ProjectCreateWithoutImagesInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
  awards?: Prisma.ProjectAwardCreateNestedManyWithoutProjectInput
  skills?: Prisma.TechSkillCreateNestedManyWithoutProjectsInput
}

export type ProjectUncheckedCreateWithoutImagesInput = {
  id?: string
  name?: string
  short_desc?: string
  long_desc?: string
  overview_desc?: string
  architecture_desc?: string
  practiced_skills_desc?: string
  goal_desc?: string
  project_phase?: string | null
  video_preview?: string | null
  github_url?: string | null
  website_url?: string | null
  website_logo_url?: string | null
  docs_url?: string | null
  project_type?: $Enums.ProjectType
  createdAt?: Date | string
  updatedAt?: Date | string
  awards?: Prisma.ProjectAwardUncheckedCreateNestedManyWithoutProjectInput
  skills?: Prisma.TechSkillUncheckedCreateNestedManyWithoutProjectsInput
}

export type ProjectCreateOrConnectWithoutImagesInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutImagesInput, Prisma.ProjectUncheckedCreateWithoutImagesInput>
}

export type ProjectUpsertWithoutImagesInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutImagesInput, Prisma.ProjectUncheckedUpdateWithoutImagesInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutImagesInput, Prisma.ProjectUncheckedCreateWithoutImagesInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutImagesInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutImagesInput, Prisma.ProjectUncheckedUpdateWithoutImagesInput>
}

export type ProjectUpdateWithoutImagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  awards?: Prisma.ProjectAwardUpdateManyWithoutProjectNestedInput
  skills?: Prisma.TechSkillUpdateManyWithoutProjectsNestedInput
}

export type ProjectUncheckedUpdateWithoutImagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  awards?: Prisma.ProjectAwardUncheckedUpdateManyWithoutProjectNestedInput
  skills?: Prisma.TechSkillUncheckedUpdateManyWithoutProjectsNestedInput
}

export type ProjectUpdateWithoutSkillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProjectImagesUpdateOneWithoutProjectNestedInput
  awards?: Prisma.ProjectAwardUpdateManyWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutSkillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  images?: Prisma.ProjectImagesUncheckedUpdateOneWithoutProjectNestedInput
  awards?: Prisma.ProjectAwardUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateManyWithoutSkillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  short_desc?: Prisma.StringFieldUpdateOperationsInput | string
  long_desc?: Prisma.StringFieldUpdateOperationsInput | string
  overview_desc?: Prisma.StringFieldUpdateOperationsInput | string
  architecture_desc?: Prisma.StringFieldUpdateOperationsInput | string
  practiced_skills_desc?: Prisma.StringFieldUpdateOperationsInput | string
  goal_desc?: Prisma.StringFieldUpdateOperationsInput | string
  project_phase?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video_preview?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  github_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  website_logo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  docs_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project_type?: Prisma.EnumProjectTypeFieldUpdateOperationsInput | $Enums.ProjectType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProjectCountOutputType
 */

export type ProjectCountOutputType = {
  awards: number
  skills: number
}

export type ProjectCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  awards?: boolean | ProjectCountOutputTypeCountAwardsArgs
  skills?: boolean | ProjectCountOutputTypeCountSkillsArgs
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCountOutputType
   */
  select?: Prisma.ProjectCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountAwardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectAwardWhereInput
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountSkillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TechSkillWhereInput
}


export type ProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  short_desc?: boolean
  long_desc?: boolean
  overview_desc?: boolean
  architecture_desc?: boolean
  practiced_skills_desc?: boolean
  goal_desc?: boolean
  project_phase?: boolean
  video_preview?: boolean
  github_url?: boolean
  website_url?: boolean
  website_logo_url?: boolean
  docs_url?: boolean
  project_type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  images?: boolean | Prisma.Project$imagesArgs<ExtArgs>
  awards?: boolean | Prisma.Project$awardsArgs<ExtArgs>
  skills?: boolean | Prisma.Project$skillsArgs<ExtArgs>
  _count?: boolean | Prisma.ProjectCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["project"]>

export type ProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  short_desc?: boolean
  long_desc?: boolean
  overview_desc?: boolean
  architecture_desc?: boolean
  practiced_skills_desc?: boolean
  goal_desc?: boolean
  project_phase?: boolean
  video_preview?: boolean
  github_url?: boolean
  website_url?: boolean
  website_logo_url?: boolean
  docs_url?: boolean
  project_type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["project"]>

export type ProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  short_desc?: boolean
  long_desc?: boolean
  overview_desc?: boolean
  architecture_desc?: boolean
  practiced_skills_desc?: boolean
  goal_desc?: boolean
  project_phase?: boolean
  video_preview?: boolean
  github_url?: boolean
  website_url?: boolean
  website_logo_url?: boolean
  docs_url?: boolean
  project_type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["project"]>

export type ProjectSelectScalar = {
  id?: boolean
  name?: boolean
  short_desc?: boolean
  long_desc?: boolean
  overview_desc?: boolean
  architecture_desc?: boolean
  practiced_skills_desc?: boolean
  goal_desc?: boolean
  project_phase?: boolean
  video_preview?: boolean
  github_url?: boolean
  website_url?: boolean
  website_logo_url?: boolean
  docs_url?: boolean
  project_type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "short_desc" | "long_desc" | "overview_desc" | "architecture_desc" | "practiced_skills_desc" | "goal_desc" | "project_phase" | "video_preview" | "github_url" | "website_url" | "website_logo_url" | "docs_url" | "project_type" | "createdAt" | "updatedAt", ExtArgs["result"]["project"]>
export type ProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  images?: boolean | Prisma.Project$imagesArgs<ExtArgs>
  awards?: boolean | Prisma.Project$awardsArgs<ExtArgs>
  skills?: boolean | Prisma.Project$skillsArgs<ExtArgs>
  _count?: boolean | Prisma.ProjectCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Project"
  objects: {
    images: Prisma.$ProjectImagesPayload<ExtArgs> | null
    awards: Prisma.$ProjectAwardPayload<ExtArgs>[]
    skills: Prisma.$TechSkillPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    short_desc: string
    long_desc: string
    overview_desc: string
    architecture_desc: string
    practiced_skills_desc: string
    goal_desc: string
    project_phase: string | null
    video_preview: string | null
    github_url: string | null
    website_url: string | null
    website_logo_url: string | null
    docs_url: string | null
    project_type: $Enums.ProjectType
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["project"]>
  composites: {}
}

export type ProjectGetPayload<S extends boolean | null | undefined | ProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjectPayload, S>

export type ProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjectCountAggregateInputType | true
  }

export interface ProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Project'], meta: { name: 'Project' } }
  /**
   * Find zero or one Project that matches the filter.
   * @param {ProjectFindUniqueArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Project that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjectFindUniqueOrThrowArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Project that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindFirstArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Project that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindFirstOrThrowArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Projects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Projects
   * const projects = await prisma.project.findMany()
   * 
   * // Get first 10 Projects
   * const projects = await prisma.project.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projectWithIdOnly = await prisma.project.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjectFindManyArgs>(args?: Prisma.SelectSubset<T, ProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Project.
   * @param {ProjectCreateArgs} args - Arguments to create a Project.
   * @example
   * // Create one Project
   * const Project = await prisma.project.create({
   *   data: {
   *     // ... data to create a Project
   *   }
   * })
   * 
   */
  create<T extends ProjectCreateArgs>(args: Prisma.SelectSubset<T, ProjectCreateArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Projects.
   * @param {ProjectCreateManyArgs} args - Arguments to create many Projects.
   * @example
   * // Create many Projects
   * const project = await prisma.project.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Projects and returns the data saved in the database.
   * @param {ProjectCreateManyAndReturnArgs} args - Arguments to create many Projects.
   * @example
   * // Create many Projects
   * const project = await prisma.project.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Projects and only return the `id`
   * const projectWithIdOnly = await prisma.project.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Project.
   * @param {ProjectDeleteArgs} args - Arguments to delete one Project.
   * @example
   * // Delete one Project
   * const Project = await prisma.project.delete({
   *   where: {
   *     // ... filter to delete one Project
   *   }
   * })
   * 
   */
  delete<T extends ProjectDeleteArgs>(args: Prisma.SelectSubset<T, ProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Project.
   * @param {ProjectUpdateArgs} args - Arguments to update one Project.
   * @example
   * // Update one Project
   * const project = await prisma.project.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjectUpdateArgs>(args: Prisma.SelectSubset<T, ProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Projects.
   * @param {ProjectDeleteManyArgs} args - Arguments to filter Projects to delete.
   * @example
   * // Delete a few Projects
   * const { count } = await prisma.project.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Projects
   * const project = await prisma.project.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projects and returns the data updated in the database.
   * @param {ProjectUpdateManyAndReturnArgs} args - Arguments to update many Projects.
   * @example
   * // Update many Projects
   * const project = await prisma.project.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Projects and only return the `id`
   * const projectWithIdOnly = await prisma.project.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Project.
   * @param {ProjectUpsertArgs} args - Arguments to update or create a Project.
   * @example
   * // Update or create a Project
   * const project = await prisma.project.upsert({
   *   create: {
   *     // ... data to create a Project
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Project we want to update
   *   }
   * })
   */
  upsert<T extends ProjectUpsertArgs>(args: Prisma.SelectSubset<T, ProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCountArgs} args - Arguments to filter Projects to count.
   * @example
   * // Count the number of Projects
   * const count = await prisma.project.count({
   *   where: {
   *     // ... the filter for the Projects we want to count
   *   }
   * })
  **/
  count<T extends ProjectCountArgs>(
    args?: Prisma.Subset<T, ProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjectAggregateArgs>(args: Prisma.Subset<T, ProjectAggregateArgs>): Prisma.PrismaPromise<GetProjectAggregateType<T>>

  /**
   * Group by Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjectGroupByArgs['orderBy'] }
      : { orderBy?: ProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Project model
 */
readonly fields: ProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Project.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  images<T extends Prisma.Project$imagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$imagesArgs<ExtArgs>>): Prisma.Prisma__ProjectImagesClient<runtime.Types.Result.GetResult<Prisma.$ProjectImagesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  awards<T extends Prisma.Project$awardsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$awardsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  skills<T extends Prisma.Project$skillsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$skillsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Project model
 */
export interface ProjectFieldRefs {
  readonly id: Prisma.FieldRef<"Project", 'String'>
  readonly name: Prisma.FieldRef<"Project", 'String'>
  readonly short_desc: Prisma.FieldRef<"Project", 'String'>
  readonly long_desc: Prisma.FieldRef<"Project", 'String'>
  readonly overview_desc: Prisma.FieldRef<"Project", 'String'>
  readonly architecture_desc: Prisma.FieldRef<"Project", 'String'>
  readonly practiced_skills_desc: Prisma.FieldRef<"Project", 'String'>
  readonly goal_desc: Prisma.FieldRef<"Project", 'String'>
  readonly project_phase: Prisma.FieldRef<"Project", 'String'>
  readonly video_preview: Prisma.FieldRef<"Project", 'String'>
  readonly github_url: Prisma.FieldRef<"Project", 'String'>
  readonly website_url: Prisma.FieldRef<"Project", 'String'>
  readonly website_logo_url: Prisma.FieldRef<"Project", 'String'>
  readonly docs_url: Prisma.FieldRef<"Project", 'String'>
  readonly project_type: Prisma.FieldRef<"Project", 'ProjectType'>
  readonly createdAt: Prisma.FieldRef<"Project", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Project", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Project findUnique
 */
export type ProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project findUniqueOrThrow
 */
export type ProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project findFirst
 */
export type ProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project findFirstOrThrow
 */
export type ProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project findMany
 */
export type ProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Projects to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project create
 */
export type ProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a Project.
   */
  data: Prisma.XOR<Prisma.ProjectCreateInput, Prisma.ProjectUncheckedCreateInput>
}

/**
 * Project createMany
 */
export type ProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Projects.
   */
  data: Prisma.ProjectCreateManyInput | Prisma.ProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Project createManyAndReturn
 */
export type ProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * The data used to create many Projects.
   */
  data: Prisma.ProjectCreateManyInput | Prisma.ProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Project update
 */
export type ProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a Project.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateInput, Prisma.ProjectUncheckedUpdateInput>
  /**
   * Choose, which Project to update.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project updateMany
 */
export type ProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Projects.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Projects to update
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to update.
   */
  limit?: number
}

/**
 * Project updateManyAndReturn
 */
export type ProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * The data used to update Projects.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Projects to update
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to update.
   */
  limit?: number
}

/**
 * Project upsert
 */
export type ProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the Project to update in case it exists.
   */
  where: Prisma.ProjectWhereUniqueInput
  /**
   * In case the Project found by the `where` argument doesn't exist, create a new Project with this data.
   */
  create: Prisma.XOR<Prisma.ProjectCreateInput, Prisma.ProjectUncheckedCreateInput>
  /**
   * In case the Project was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjectUpdateInput, Prisma.ProjectUncheckedUpdateInput>
}

/**
 * Project delete
 */
export type ProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter which Project to delete.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project deleteMany
 */
export type ProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Projects to delete
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to delete.
   */
  limit?: number
}

/**
 * Project.images
 */
export type Project$imagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectImages
   */
  select?: Prisma.ProjectImagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectImages
   */
  omit?: Prisma.ProjectImagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectImagesInclude<ExtArgs> | null
  where?: Prisma.ProjectImagesWhereInput
}

/**
 * Project.awards
 */
export type Project$awardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  where?: Prisma.ProjectAwardWhereInput
  orderBy?: Prisma.ProjectAwardOrderByWithRelationInput | Prisma.ProjectAwardOrderByWithRelationInput[]
  cursor?: Prisma.ProjectAwardWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProjectAwardScalarFieldEnum | Prisma.ProjectAwardScalarFieldEnum[]
}

/**
 * Project.skills
 */
export type Project$skillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  where?: Prisma.TechSkillWhereInput
  orderBy?: Prisma.TechSkillOrderByWithRelationInput | Prisma.TechSkillOrderByWithRelationInput[]
  cursor?: Prisma.TechSkillWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TechSkillScalarFieldEnum | Prisma.TechSkillScalarFieldEnum[]
}

/**
 * Project without action
 */
export type ProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
}
