
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProjectAward` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProjectAward
 * 
 */
export type ProjectAwardModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjectAwardPayload>

export type AggregateProjectAward = {
  _count: ProjectAwardCountAggregateOutputType | null
  _min: ProjectAwardMinAggregateOutputType | null
  _max: ProjectAwardMaxAggregateOutputType | null
}

export type ProjectAwardMinAggregateOutputType = {
  id: string | null
  project_id: string | null
  image_src: string | null
  desc: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectAwardMaxAggregateOutputType = {
  id: string | null
  project_id: string | null
  image_src: string | null
  desc: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectAwardCountAggregateOutputType = {
  id: number
  project_id: number
  image_src: number
  desc: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProjectAwardMinAggregateInputType = {
  id?: true
  project_id?: true
  image_src?: true
  desc?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectAwardMaxAggregateInputType = {
  id?: true
  project_id?: true
  image_src?: true
  desc?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectAwardCountAggregateInputType = {
  id?: true
  project_id?: true
  image_src?: true
  desc?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProjectAwardAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProjectAward to aggregate.
   */
  where?: Prisma.ProjectAwardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectAwards to fetch.
   */
  orderBy?: Prisma.ProjectAwardOrderByWithRelationInput | Prisma.ProjectAwardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjectAwardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectAwards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectAwards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProjectAwards
  **/
  _count?: true | ProjectAwardCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjectAwardMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjectAwardMaxAggregateInputType
}

export type GetProjectAwardAggregateType<T extends ProjectAwardAggregateArgs> = {
      [P in keyof T & keyof AggregateProjectAward]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProjectAward[P]>
    : Prisma.GetScalarType<T[P], AggregateProjectAward[P]>
}




export type ProjectAwardGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectAwardWhereInput
  orderBy?: Prisma.ProjectAwardOrderByWithAggregationInput | Prisma.ProjectAwardOrderByWithAggregationInput[]
  by: Prisma.ProjectAwardScalarFieldEnum[] | Prisma.ProjectAwardScalarFieldEnum
  having?: Prisma.ProjectAwardScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjectAwardCountAggregateInputType | true
  _min?: ProjectAwardMinAggregateInputType
  _max?: ProjectAwardMaxAggregateInputType
}

export type ProjectAwardGroupByOutputType = {
  id: string
  project_id: string
  image_src: string
  desc: string
  createdAt: Date
  updatedAt: Date
  _count: ProjectAwardCountAggregateOutputType | null
  _min: ProjectAwardMinAggregateOutputType | null
  _max: ProjectAwardMaxAggregateOutputType | null
}

export type GetProjectAwardGroupByPayload<T extends ProjectAwardGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjectAwardGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjectAwardGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjectAwardGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjectAwardGroupByOutputType[P]>
      }
    >
  >



export type ProjectAwardWhereInput = {
  AND?: Prisma.ProjectAwardWhereInput | Prisma.ProjectAwardWhereInput[]
  OR?: Prisma.ProjectAwardWhereInput[]
  NOT?: Prisma.ProjectAwardWhereInput | Prisma.ProjectAwardWhereInput[]
  id?: Prisma.StringFilter<"ProjectAward"> | string
  project_id?: Prisma.StringFilter<"ProjectAward"> | string
  image_src?: Prisma.StringFilter<"ProjectAward"> | string
  desc?: Prisma.StringFilter<"ProjectAward"> | string
  createdAt?: Prisma.DateTimeFilter<"ProjectAward"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProjectAward"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type ProjectAwardOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  project_id?: Prisma.SortOrder
  image_src?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type ProjectAwardWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProjectAwardWhereInput | Prisma.ProjectAwardWhereInput[]
  OR?: Prisma.ProjectAwardWhereInput[]
  NOT?: Prisma.ProjectAwardWhereInput | Prisma.ProjectAwardWhereInput[]
  project_id?: Prisma.StringFilter<"ProjectAward"> | string
  image_src?: Prisma.StringFilter<"ProjectAward"> | string
  desc?: Prisma.StringFilter<"ProjectAward"> | string
  createdAt?: Prisma.DateTimeFilter<"ProjectAward"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProjectAward"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id">

export type ProjectAwardOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  project_id?: Prisma.SortOrder
  image_src?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProjectAwardCountOrderByAggregateInput
  _max?: Prisma.ProjectAwardMaxOrderByAggregateInput
  _min?: Prisma.ProjectAwardMinOrderByAggregateInput
}

export type ProjectAwardScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjectAwardScalarWhereWithAggregatesInput | Prisma.ProjectAwardScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjectAwardScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjectAwardScalarWhereWithAggregatesInput | Prisma.ProjectAwardScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProjectAward"> | string
  project_id?: Prisma.StringWithAggregatesFilter<"ProjectAward"> | string
  image_src?: Prisma.StringWithAggregatesFilter<"ProjectAward"> | string
  desc?: Prisma.StringWithAggregatesFilter<"ProjectAward"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProjectAward"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ProjectAward"> | Date | string
}

export type ProjectAwardCreateInput = {
  id?: string
  image_src?: string
  desc?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutAwardsInput
}

export type ProjectAwardUncheckedCreateInput = {
  id?: string
  project_id: string
  image_src?: string
  desc?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectAwardUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  image_src?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutAwardsNestedInput
}

export type ProjectAwardUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  project_id?: Prisma.StringFieldUpdateOperationsInput | string
  image_src?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectAwardCreateManyInput = {
  id?: string
  project_id: string
  image_src?: string
  desc?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectAwardUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  image_src?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectAwardUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  project_id?: Prisma.StringFieldUpdateOperationsInput | string
  image_src?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectAwardCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  project_id?: Prisma.SortOrder
  image_src?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectAwardMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  project_id?: Prisma.SortOrder
  image_src?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectAwardMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  project_id?: Prisma.SortOrder
  image_src?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectAwardListRelationFilter = {
  every?: Prisma.ProjectAwardWhereInput
  some?: Prisma.ProjectAwardWhereInput
  none?: Prisma.ProjectAwardWhereInput
}

export type ProjectAwardOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProjectAwardCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ProjectAwardCreateWithoutProjectInput, Prisma.ProjectAwardUncheckedCreateWithoutProjectInput> | Prisma.ProjectAwardCreateWithoutProjectInput[] | Prisma.ProjectAwardUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectAwardCreateOrConnectWithoutProjectInput | Prisma.ProjectAwardCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ProjectAwardCreateManyProjectInputEnvelope
  connect?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
}

export type ProjectAwardUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ProjectAwardCreateWithoutProjectInput, Prisma.ProjectAwardUncheckedCreateWithoutProjectInput> | Prisma.ProjectAwardCreateWithoutProjectInput[] | Prisma.ProjectAwardUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectAwardCreateOrConnectWithoutProjectInput | Prisma.ProjectAwardCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ProjectAwardCreateManyProjectInputEnvelope
  connect?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
}

export type ProjectAwardUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectAwardCreateWithoutProjectInput, Prisma.ProjectAwardUncheckedCreateWithoutProjectInput> | Prisma.ProjectAwardCreateWithoutProjectInput[] | Prisma.ProjectAwardUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectAwardCreateOrConnectWithoutProjectInput | Prisma.ProjectAwardCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ProjectAwardUpsertWithWhereUniqueWithoutProjectInput | Prisma.ProjectAwardUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ProjectAwardCreateManyProjectInputEnvelope
  set?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
  disconnect?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
  delete?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
  connect?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
  update?: Prisma.ProjectAwardUpdateWithWhereUniqueWithoutProjectInput | Prisma.ProjectAwardUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ProjectAwardUpdateManyWithWhereWithoutProjectInput | Prisma.ProjectAwardUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ProjectAwardScalarWhereInput | Prisma.ProjectAwardScalarWhereInput[]
}

export type ProjectAwardUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectAwardCreateWithoutProjectInput, Prisma.ProjectAwardUncheckedCreateWithoutProjectInput> | Prisma.ProjectAwardCreateWithoutProjectInput[] | Prisma.ProjectAwardUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectAwardCreateOrConnectWithoutProjectInput | Prisma.ProjectAwardCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ProjectAwardUpsertWithWhereUniqueWithoutProjectInput | Prisma.ProjectAwardUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ProjectAwardCreateManyProjectInputEnvelope
  set?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
  disconnect?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
  delete?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
  connect?: Prisma.ProjectAwardWhereUniqueInput | Prisma.ProjectAwardWhereUniqueInput[]
  update?: Prisma.ProjectAwardUpdateWithWhereUniqueWithoutProjectInput | Prisma.ProjectAwardUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ProjectAwardUpdateManyWithWhereWithoutProjectInput | Prisma.ProjectAwardUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ProjectAwardScalarWhereInput | Prisma.ProjectAwardScalarWhereInput[]
}

export type ProjectAwardCreateWithoutProjectInput = {
  id?: string
  image_src?: string
  desc?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectAwardUncheckedCreateWithoutProjectInput = {
  id?: string
  image_src?: string
  desc?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectAwardCreateOrConnectWithoutProjectInput = {
  where: Prisma.ProjectAwardWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectAwardCreateWithoutProjectInput, Prisma.ProjectAwardUncheckedCreateWithoutProjectInput>
}

export type ProjectAwardCreateManyProjectInputEnvelope = {
  data: Prisma.ProjectAwardCreateManyProjectInput | Prisma.ProjectAwardCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type ProjectAwardUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ProjectAwardWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectAwardUpdateWithoutProjectInput, Prisma.ProjectAwardUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.ProjectAwardCreateWithoutProjectInput, Prisma.ProjectAwardUncheckedCreateWithoutProjectInput>
}

export type ProjectAwardUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ProjectAwardWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectAwardUpdateWithoutProjectInput, Prisma.ProjectAwardUncheckedUpdateWithoutProjectInput>
}

export type ProjectAwardUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.ProjectAwardScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectAwardUpdateManyMutationInput, Prisma.ProjectAwardUncheckedUpdateManyWithoutProjectInput>
}

export type ProjectAwardScalarWhereInput = {
  AND?: Prisma.ProjectAwardScalarWhereInput | Prisma.ProjectAwardScalarWhereInput[]
  OR?: Prisma.ProjectAwardScalarWhereInput[]
  NOT?: Prisma.ProjectAwardScalarWhereInput | Prisma.ProjectAwardScalarWhereInput[]
  id?: Prisma.StringFilter<"ProjectAward"> | string
  project_id?: Prisma.StringFilter<"ProjectAward"> | string
  image_src?: Prisma.StringFilter<"ProjectAward"> | string
  desc?: Prisma.StringFilter<"ProjectAward"> | string
  createdAt?: Prisma.DateTimeFilter<"ProjectAward"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProjectAward"> | Date | string
}

export type ProjectAwardCreateManyProjectInput = {
  id?: string
  image_src?: string
  desc?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectAwardUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  image_src?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectAwardUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  image_src?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectAwardUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  image_src?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProjectAwardSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  project_id?: boolean
  image_src?: boolean
  desc?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectAward"]>

export type ProjectAwardSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  project_id?: boolean
  image_src?: boolean
  desc?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectAward"]>

export type ProjectAwardSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  project_id?: boolean
  image_src?: boolean
  desc?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectAward"]>

export type ProjectAwardSelectScalar = {
  id?: boolean
  project_id?: boolean
  image_src?: boolean
  desc?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProjectAwardOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "project_id" | "image_src" | "desc" | "createdAt" | "updatedAt", ExtArgs["result"]["projectAward"]>
export type ProjectAwardInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type ProjectAwardIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type ProjectAwardIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $ProjectAwardPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProjectAward"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    project_id: string
    image_src: string
    desc: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["projectAward"]>
  composites: {}
}

export type ProjectAwardGetPayload<S extends boolean | null | undefined | ProjectAwardDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload, S>

export type ProjectAwardCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjectAwardFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjectAwardCountAggregateInputType | true
  }

export interface ProjectAwardDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProjectAward'], meta: { name: 'ProjectAward' } }
  /**
   * Find zero or one ProjectAward that matches the filter.
   * @param {ProjectAwardFindUniqueArgs} args - Arguments to find a ProjectAward
   * @example
   * // Get one ProjectAward
   * const projectAward = await prisma.projectAward.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjectAwardFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjectAwardFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjectAwardClient<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProjectAward that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjectAwardFindUniqueOrThrowArgs} args - Arguments to find a ProjectAward
   * @example
   * // Get one ProjectAward
   * const projectAward = await prisma.projectAward.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjectAwardFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjectAwardFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectAwardClient<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProjectAward that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAwardFindFirstArgs} args - Arguments to find a ProjectAward
   * @example
   * // Get one ProjectAward
   * const projectAward = await prisma.projectAward.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjectAwardFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjectAwardFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjectAwardClient<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProjectAward that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAwardFindFirstOrThrowArgs} args - Arguments to find a ProjectAward
   * @example
   * // Get one ProjectAward
   * const projectAward = await prisma.projectAward.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjectAwardFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjectAwardFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectAwardClient<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProjectAwards that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAwardFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProjectAwards
   * const projectAwards = await prisma.projectAward.findMany()
   * 
   * // Get first 10 ProjectAwards
   * const projectAwards = await prisma.projectAward.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projectAwardWithIdOnly = await prisma.projectAward.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjectAwardFindManyArgs>(args?: Prisma.SelectSubset<T, ProjectAwardFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProjectAward.
   * @param {ProjectAwardCreateArgs} args - Arguments to create a ProjectAward.
   * @example
   * // Create one ProjectAward
   * const ProjectAward = await prisma.projectAward.create({
   *   data: {
   *     // ... data to create a ProjectAward
   *   }
   * })
   * 
   */
  create<T extends ProjectAwardCreateArgs>(args: Prisma.SelectSubset<T, ProjectAwardCreateArgs<ExtArgs>>): Prisma.Prisma__ProjectAwardClient<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProjectAwards.
   * @param {ProjectAwardCreateManyArgs} args - Arguments to create many ProjectAwards.
   * @example
   * // Create many ProjectAwards
   * const projectAward = await prisma.projectAward.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjectAwardCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjectAwardCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProjectAwards and returns the data saved in the database.
   * @param {ProjectAwardCreateManyAndReturnArgs} args - Arguments to create many ProjectAwards.
   * @example
   * // Create many ProjectAwards
   * const projectAward = await prisma.projectAward.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProjectAwards and only return the `id`
   * const projectAwardWithIdOnly = await prisma.projectAward.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjectAwardCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjectAwardCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProjectAward.
   * @param {ProjectAwardDeleteArgs} args - Arguments to delete one ProjectAward.
   * @example
   * // Delete one ProjectAward
   * const ProjectAward = await prisma.projectAward.delete({
   *   where: {
   *     // ... filter to delete one ProjectAward
   *   }
   * })
   * 
   */
  delete<T extends ProjectAwardDeleteArgs>(args: Prisma.SelectSubset<T, ProjectAwardDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjectAwardClient<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProjectAward.
   * @param {ProjectAwardUpdateArgs} args - Arguments to update one ProjectAward.
   * @example
   * // Update one ProjectAward
   * const projectAward = await prisma.projectAward.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjectAwardUpdateArgs>(args: Prisma.SelectSubset<T, ProjectAwardUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjectAwardClient<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProjectAwards.
   * @param {ProjectAwardDeleteManyArgs} args - Arguments to filter ProjectAwards to delete.
   * @example
   * // Delete a few ProjectAwards
   * const { count } = await prisma.projectAward.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjectAwardDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjectAwardDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProjectAwards.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAwardUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProjectAwards
   * const projectAward = await prisma.projectAward.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjectAwardUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjectAwardUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProjectAwards and returns the data updated in the database.
   * @param {ProjectAwardUpdateManyAndReturnArgs} args - Arguments to update many ProjectAwards.
   * @example
   * // Update many ProjectAwards
   * const projectAward = await prisma.projectAward.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProjectAwards and only return the `id`
   * const projectAwardWithIdOnly = await prisma.projectAward.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjectAwardUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjectAwardUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProjectAward.
   * @param {ProjectAwardUpsertArgs} args - Arguments to update or create a ProjectAward.
   * @example
   * // Update or create a ProjectAward
   * const projectAward = await prisma.projectAward.upsert({
   *   create: {
   *     // ... data to create a ProjectAward
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProjectAward we want to update
   *   }
   * })
   */
  upsert<T extends ProjectAwardUpsertArgs>(args: Prisma.SelectSubset<T, ProjectAwardUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjectAwardClient<runtime.Types.Result.GetResult<Prisma.$ProjectAwardPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProjectAwards.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAwardCountArgs} args - Arguments to filter ProjectAwards to count.
   * @example
   * // Count the number of ProjectAwards
   * const count = await prisma.projectAward.count({
   *   where: {
   *     // ... the filter for the ProjectAwards we want to count
   *   }
   * })
  **/
  count<T extends ProjectAwardCountArgs>(
    args?: Prisma.Subset<T, ProjectAwardCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjectAwardCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProjectAward.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAwardAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjectAwardAggregateArgs>(args: Prisma.Subset<T, ProjectAwardAggregateArgs>): Prisma.PrismaPromise<GetProjectAwardAggregateType<T>>

  /**
   * Group by ProjectAward.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAwardGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjectAwardGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjectAwardGroupByArgs['orderBy'] }
      : { orderBy?: ProjectAwardGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjectAwardGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjectAwardGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProjectAward model
 */
readonly fields: ProjectAwardFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProjectAward.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjectAwardClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProjectAward model
 */
export interface ProjectAwardFieldRefs {
  readonly id: Prisma.FieldRef<"ProjectAward", 'String'>
  readonly project_id: Prisma.FieldRef<"ProjectAward", 'String'>
  readonly image_src: Prisma.FieldRef<"ProjectAward", 'String'>
  readonly desc: Prisma.FieldRef<"ProjectAward", 'String'>
  readonly createdAt: Prisma.FieldRef<"ProjectAward", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ProjectAward", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProjectAward findUnique
 */
export type ProjectAwardFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * Filter, which ProjectAward to fetch.
   */
  where: Prisma.ProjectAwardWhereUniqueInput
}

/**
 * ProjectAward findUniqueOrThrow
 */
export type ProjectAwardFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * Filter, which ProjectAward to fetch.
   */
  where: Prisma.ProjectAwardWhereUniqueInput
}

/**
 * ProjectAward findFirst
 */
export type ProjectAwardFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * Filter, which ProjectAward to fetch.
   */
  where?: Prisma.ProjectAwardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectAwards to fetch.
   */
  orderBy?: Prisma.ProjectAwardOrderByWithRelationInput | Prisma.ProjectAwardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProjectAwards.
   */
  cursor?: Prisma.ProjectAwardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectAwards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectAwards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectAwards.
   */
  distinct?: Prisma.ProjectAwardScalarFieldEnum | Prisma.ProjectAwardScalarFieldEnum[]
}

/**
 * ProjectAward findFirstOrThrow
 */
export type ProjectAwardFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * Filter, which ProjectAward to fetch.
   */
  where?: Prisma.ProjectAwardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectAwards to fetch.
   */
  orderBy?: Prisma.ProjectAwardOrderByWithRelationInput | Prisma.ProjectAwardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProjectAwards.
   */
  cursor?: Prisma.ProjectAwardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectAwards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectAwards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectAwards.
   */
  distinct?: Prisma.ProjectAwardScalarFieldEnum | Prisma.ProjectAwardScalarFieldEnum[]
}

/**
 * ProjectAward findMany
 */
export type ProjectAwardFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * Filter, which ProjectAwards to fetch.
   */
  where?: Prisma.ProjectAwardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectAwards to fetch.
   */
  orderBy?: Prisma.ProjectAwardOrderByWithRelationInput | Prisma.ProjectAwardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProjectAwards.
   */
  cursor?: Prisma.ProjectAwardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectAwards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectAwards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectAwards.
   */
  distinct?: Prisma.ProjectAwardScalarFieldEnum | Prisma.ProjectAwardScalarFieldEnum[]
}

/**
 * ProjectAward create
 */
export type ProjectAwardCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * The data needed to create a ProjectAward.
   */
  data: Prisma.XOR<Prisma.ProjectAwardCreateInput, Prisma.ProjectAwardUncheckedCreateInput>
}

/**
 * ProjectAward createMany
 */
export type ProjectAwardCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProjectAwards.
   */
  data: Prisma.ProjectAwardCreateManyInput | Prisma.ProjectAwardCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProjectAward createManyAndReturn
 */
export type ProjectAwardCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * The data used to create many ProjectAwards.
   */
  data: Prisma.ProjectAwardCreateManyInput | Prisma.ProjectAwardCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProjectAward update
 */
export type ProjectAwardUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * The data needed to update a ProjectAward.
   */
  data: Prisma.XOR<Prisma.ProjectAwardUpdateInput, Prisma.ProjectAwardUncheckedUpdateInput>
  /**
   * Choose, which ProjectAward to update.
   */
  where: Prisma.ProjectAwardWhereUniqueInput
}

/**
 * ProjectAward updateMany
 */
export type ProjectAwardUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProjectAwards.
   */
  data: Prisma.XOR<Prisma.ProjectAwardUpdateManyMutationInput, Prisma.ProjectAwardUncheckedUpdateManyInput>
  /**
   * Filter which ProjectAwards to update
   */
  where?: Prisma.ProjectAwardWhereInput
  /**
   * Limit how many ProjectAwards to update.
   */
  limit?: number
}

/**
 * ProjectAward updateManyAndReturn
 */
export type ProjectAwardUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * The data used to update ProjectAwards.
   */
  data: Prisma.XOR<Prisma.ProjectAwardUpdateManyMutationInput, Prisma.ProjectAwardUncheckedUpdateManyInput>
  /**
   * Filter which ProjectAwards to update
   */
  where?: Prisma.ProjectAwardWhereInput
  /**
   * Limit how many ProjectAwards to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProjectAward upsert
 */
export type ProjectAwardUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * The filter to search for the ProjectAward to update in case it exists.
   */
  where: Prisma.ProjectAwardWhereUniqueInput
  /**
   * In case the ProjectAward found by the `where` argument doesn't exist, create a new ProjectAward with this data.
   */
  create: Prisma.XOR<Prisma.ProjectAwardCreateInput, Prisma.ProjectAwardUncheckedCreateInput>
  /**
   * In case the ProjectAward was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjectAwardUpdateInput, Prisma.ProjectAwardUncheckedUpdateInput>
}

/**
 * ProjectAward delete
 */
export type ProjectAwardDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
  /**
   * Filter which ProjectAward to delete.
   */
  where: Prisma.ProjectAwardWhereUniqueInput
}

/**
 * ProjectAward deleteMany
 */
export type ProjectAwardDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProjectAwards to delete
   */
  where?: Prisma.ProjectAwardWhereInput
  /**
   * Limit how many ProjectAwards to delete.
   */
  limit?: number
}

/**
 * ProjectAward without action
 */
export type ProjectAwardDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectAward
   */
  select?: Prisma.ProjectAwardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectAward
   */
  omit?: Prisma.ProjectAwardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectAwardInclude<ExtArgs> | null
}
