
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TechSkill` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TechSkill
 * 
 */
export type TechSkillModel = runtime.Types.Result.DefaultSelection<Prisma.$TechSkillPayload>

export type AggregateTechSkill = {
  _count: TechSkillCountAggregateOutputType | null
  _min: TechSkillMinAggregateOutputType | null
  _max: TechSkillMaxAggregateOutputType | null
}

export type TechSkillMinAggregateOutputType = {
  id: string | null
  tech_id: string | null
  scope: $Enums.TechSkillScope | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TechSkillMaxAggregateOutputType = {
  id: string | null
  tech_id: string | null
  scope: $Enums.TechSkillScope | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TechSkillCountAggregateOutputType = {
  id: number
  tech_id: number
  scope: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TechSkillMinAggregateInputType = {
  id?: true
  tech_id?: true
  scope?: true
  createdAt?: true
  updatedAt?: true
}

export type TechSkillMaxAggregateInputType = {
  id?: true
  tech_id?: true
  scope?: true
  createdAt?: true
  updatedAt?: true
}

export type TechSkillCountAggregateInputType = {
  id?: true
  tech_id?: true
  scope?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TechSkillAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TechSkill to aggregate.
   */
  where?: Prisma.TechSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechSkills to fetch.
   */
  orderBy?: Prisma.TechSkillOrderByWithRelationInput | Prisma.TechSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TechSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TechSkills
  **/
  _count?: true | TechSkillCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TechSkillMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TechSkillMaxAggregateInputType
}

export type GetTechSkillAggregateType<T extends TechSkillAggregateArgs> = {
      [P in keyof T & keyof AggregateTechSkill]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTechSkill[P]>
    : Prisma.GetScalarType<T[P], AggregateTechSkill[P]>
}




export type TechSkillGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TechSkillWhereInput
  orderBy?: Prisma.TechSkillOrderByWithAggregationInput | Prisma.TechSkillOrderByWithAggregationInput[]
  by: Prisma.TechSkillScalarFieldEnum[] | Prisma.TechSkillScalarFieldEnum
  having?: Prisma.TechSkillScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TechSkillCountAggregateInputType | true
  _min?: TechSkillMinAggregateInputType
  _max?: TechSkillMaxAggregateInputType
}

export type TechSkillGroupByOutputType = {
  id: string
  tech_id: string
  scope: $Enums.TechSkillScope
  createdAt: Date
  updatedAt: Date
  _count: TechSkillCountAggregateOutputType | null
  _min: TechSkillMinAggregateOutputType | null
  _max: TechSkillMaxAggregateOutputType | null
}

export type GetTechSkillGroupByPayload<T extends TechSkillGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TechSkillGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TechSkillGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TechSkillGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TechSkillGroupByOutputType[P]>
      }
    >
  >



export type TechSkillWhereInput = {
  AND?: Prisma.TechSkillWhereInput | Prisma.TechSkillWhereInput[]
  OR?: Prisma.TechSkillWhereInput[]
  NOT?: Prisma.TechSkillWhereInput | Prisma.TechSkillWhereInput[]
  id?: Prisma.StringFilter<"TechSkill"> | string
  tech_id?: Prisma.StringFilter<"TechSkill"> | string
  scope?: Prisma.EnumTechSkillScopeFilter<"TechSkill"> | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFilter<"TechSkill"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TechSkill"> | Date | string
  tech?: Prisma.XOR<Prisma.TechScalarRelationFilter, Prisma.TechWhereInput>
  content?: Prisma.XOR<Prisma.TechSkillContentNullableScalarRelationFilter, Prisma.TechSkillContentWhereInput> | null
  projects?: Prisma.ProjectListRelationFilter
}

export type TechSkillOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tech_id?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tech?: Prisma.TechOrderByWithRelationInput
  content?: Prisma.TechSkillContentOrderByWithRelationInput
  projects?: Prisma.ProjectOrderByRelationAggregateInput
}

export type TechSkillWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  tech_id?: string
  tech_id_scope?: Prisma.TechSkillTech_idScopeCompoundUniqueInput
  AND?: Prisma.TechSkillWhereInput | Prisma.TechSkillWhereInput[]
  OR?: Prisma.TechSkillWhereInput[]
  NOT?: Prisma.TechSkillWhereInput | Prisma.TechSkillWhereInput[]
  scope?: Prisma.EnumTechSkillScopeFilter<"TechSkill"> | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFilter<"TechSkill"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TechSkill"> | Date | string
  tech?: Prisma.XOR<Prisma.TechScalarRelationFilter, Prisma.TechWhereInput>
  content?: Prisma.XOR<Prisma.TechSkillContentNullableScalarRelationFilter, Prisma.TechSkillContentWhereInput> | null
  projects?: Prisma.ProjectListRelationFilter
}, "id" | "tech_id" | "tech_id_scope">

export type TechSkillOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tech_id?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TechSkillCountOrderByAggregateInput
  _max?: Prisma.TechSkillMaxOrderByAggregateInput
  _min?: Prisma.TechSkillMinOrderByAggregateInput
}

export type TechSkillScalarWhereWithAggregatesInput = {
  AND?: Prisma.TechSkillScalarWhereWithAggregatesInput | Prisma.TechSkillScalarWhereWithAggregatesInput[]
  OR?: Prisma.TechSkillScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TechSkillScalarWhereWithAggregatesInput | Prisma.TechSkillScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TechSkill"> | string
  tech_id?: Prisma.StringWithAggregatesFilter<"TechSkill"> | string
  scope?: Prisma.EnumTechSkillScopeWithAggregatesFilter<"TechSkill"> | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TechSkill"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TechSkill"> | Date | string
}

export type TechSkillCreateInput = {
  id?: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
  tech: Prisma.TechCreateNestedOneWithoutSkillsInput
  content?: Prisma.TechSkillContentCreateNestedOneWithoutSkillInput
  projects?: Prisma.ProjectCreateNestedManyWithoutSkillsInput
}

export type TechSkillUncheckedCreateInput = {
  id?: string
  tech_id: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
  content?: Prisma.TechSkillContentUncheckedCreateNestedOneWithoutSkillInput
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutSkillsInput
}

export type TechSkillUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tech?: Prisma.TechUpdateOneRequiredWithoutSkillsNestedInput
  content?: Prisma.TechSkillContentUpdateOneWithoutSkillNestedInput
  projects?: Prisma.ProjectUpdateManyWithoutSkillsNestedInput
}

export type TechSkillUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tech_id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  content?: Prisma.TechSkillContentUncheckedUpdateOneWithoutSkillNestedInput
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutSkillsNestedInput
}

export type TechSkillCreateManyInput = {
  id?: string
  tech_id: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TechSkillUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechSkillUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tech_id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechSkillScalarRelationFilter = {
  is?: Prisma.TechSkillWhereInput
  isNot?: Prisma.TechSkillWhereInput
}

export type TechSkillTech_idScopeCompoundUniqueInput = {
  tech_id: string
  scope: $Enums.TechSkillScope
}

export type TechSkillCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tech_id?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechSkillMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tech_id?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechSkillMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tech_id?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechSkillListRelationFilter = {
  every?: Prisma.TechSkillWhereInput
  some?: Prisma.TechSkillWhereInput
  none?: Prisma.TechSkillWhereInput
}

export type TechSkillOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TechSkillCreateNestedOneWithoutContentInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutContentInput, Prisma.TechSkillUncheckedCreateWithoutContentInput>
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutContentInput
  connect?: Prisma.TechSkillWhereUniqueInput
}

export type TechSkillUpdateOneRequiredWithoutContentNestedInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutContentInput, Prisma.TechSkillUncheckedCreateWithoutContentInput>
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutContentInput
  upsert?: Prisma.TechSkillUpsertWithoutContentInput
  connect?: Prisma.TechSkillWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TechSkillUpdateToOneWithWhereWithoutContentInput, Prisma.TechSkillUpdateWithoutContentInput>, Prisma.TechSkillUncheckedUpdateWithoutContentInput>
}

export type EnumTechSkillScopeFieldUpdateOperationsInput = {
  set?: $Enums.TechSkillScope
}

export type TechSkillCreateNestedManyWithoutTechInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutTechInput, Prisma.TechSkillUncheckedCreateWithoutTechInput> | Prisma.TechSkillCreateWithoutTechInput[] | Prisma.TechSkillUncheckedCreateWithoutTechInput[]
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutTechInput | Prisma.TechSkillCreateOrConnectWithoutTechInput[]
  createMany?: Prisma.TechSkillCreateManyTechInputEnvelope
  connect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
}

export type TechSkillUncheckedCreateNestedManyWithoutTechInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutTechInput, Prisma.TechSkillUncheckedCreateWithoutTechInput> | Prisma.TechSkillCreateWithoutTechInput[] | Prisma.TechSkillUncheckedCreateWithoutTechInput[]
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutTechInput | Prisma.TechSkillCreateOrConnectWithoutTechInput[]
  createMany?: Prisma.TechSkillCreateManyTechInputEnvelope
  connect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
}

export type TechSkillUpdateManyWithoutTechNestedInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutTechInput, Prisma.TechSkillUncheckedCreateWithoutTechInput> | Prisma.TechSkillCreateWithoutTechInput[] | Prisma.TechSkillUncheckedCreateWithoutTechInput[]
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutTechInput | Prisma.TechSkillCreateOrConnectWithoutTechInput[]
  upsert?: Prisma.TechSkillUpsertWithWhereUniqueWithoutTechInput | Prisma.TechSkillUpsertWithWhereUniqueWithoutTechInput[]
  createMany?: Prisma.TechSkillCreateManyTechInputEnvelope
  set?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  disconnect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  delete?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  connect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  update?: Prisma.TechSkillUpdateWithWhereUniqueWithoutTechInput | Prisma.TechSkillUpdateWithWhereUniqueWithoutTechInput[]
  updateMany?: Prisma.TechSkillUpdateManyWithWhereWithoutTechInput | Prisma.TechSkillUpdateManyWithWhereWithoutTechInput[]
  deleteMany?: Prisma.TechSkillScalarWhereInput | Prisma.TechSkillScalarWhereInput[]
}

export type TechSkillUncheckedUpdateManyWithoutTechNestedInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutTechInput, Prisma.TechSkillUncheckedCreateWithoutTechInput> | Prisma.TechSkillCreateWithoutTechInput[] | Prisma.TechSkillUncheckedCreateWithoutTechInput[]
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutTechInput | Prisma.TechSkillCreateOrConnectWithoutTechInput[]
  upsert?: Prisma.TechSkillUpsertWithWhereUniqueWithoutTechInput | Prisma.TechSkillUpsertWithWhereUniqueWithoutTechInput[]
  createMany?: Prisma.TechSkillCreateManyTechInputEnvelope
  set?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  disconnect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  delete?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  connect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  update?: Prisma.TechSkillUpdateWithWhereUniqueWithoutTechInput | Prisma.TechSkillUpdateWithWhereUniqueWithoutTechInput[]
  updateMany?: Prisma.TechSkillUpdateManyWithWhereWithoutTechInput | Prisma.TechSkillUpdateManyWithWhereWithoutTechInput[]
  deleteMany?: Prisma.TechSkillScalarWhereInput | Prisma.TechSkillScalarWhereInput[]
}

export type TechSkillCreateNestedManyWithoutProjectsInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutProjectsInput, Prisma.TechSkillUncheckedCreateWithoutProjectsInput> | Prisma.TechSkillCreateWithoutProjectsInput[] | Prisma.TechSkillUncheckedCreateWithoutProjectsInput[]
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutProjectsInput | Prisma.TechSkillCreateOrConnectWithoutProjectsInput[]
  connect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
}

export type TechSkillUncheckedCreateNestedManyWithoutProjectsInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutProjectsInput, Prisma.TechSkillUncheckedCreateWithoutProjectsInput> | Prisma.TechSkillCreateWithoutProjectsInput[] | Prisma.TechSkillUncheckedCreateWithoutProjectsInput[]
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutProjectsInput | Prisma.TechSkillCreateOrConnectWithoutProjectsInput[]
  connect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
}

export type TechSkillUpdateManyWithoutProjectsNestedInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutProjectsInput, Prisma.TechSkillUncheckedCreateWithoutProjectsInput> | Prisma.TechSkillCreateWithoutProjectsInput[] | Prisma.TechSkillUncheckedCreateWithoutProjectsInput[]
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutProjectsInput | Prisma.TechSkillCreateOrConnectWithoutProjectsInput[]
  upsert?: Prisma.TechSkillUpsertWithWhereUniqueWithoutProjectsInput | Prisma.TechSkillUpsertWithWhereUniqueWithoutProjectsInput[]
  set?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  disconnect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  delete?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  connect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  update?: Prisma.TechSkillUpdateWithWhereUniqueWithoutProjectsInput | Prisma.TechSkillUpdateWithWhereUniqueWithoutProjectsInput[]
  updateMany?: Prisma.TechSkillUpdateManyWithWhereWithoutProjectsInput | Prisma.TechSkillUpdateManyWithWhereWithoutProjectsInput[]
  deleteMany?: Prisma.TechSkillScalarWhereInput | Prisma.TechSkillScalarWhereInput[]
}

export type TechSkillUncheckedUpdateManyWithoutProjectsNestedInput = {
  create?: Prisma.XOR<Prisma.TechSkillCreateWithoutProjectsInput, Prisma.TechSkillUncheckedCreateWithoutProjectsInput> | Prisma.TechSkillCreateWithoutProjectsInput[] | Prisma.TechSkillUncheckedCreateWithoutProjectsInput[]
  connectOrCreate?: Prisma.TechSkillCreateOrConnectWithoutProjectsInput | Prisma.TechSkillCreateOrConnectWithoutProjectsInput[]
  upsert?: Prisma.TechSkillUpsertWithWhereUniqueWithoutProjectsInput | Prisma.TechSkillUpsertWithWhereUniqueWithoutProjectsInput[]
  set?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  disconnect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  delete?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  connect?: Prisma.TechSkillWhereUniqueInput | Prisma.TechSkillWhereUniqueInput[]
  update?: Prisma.TechSkillUpdateWithWhereUniqueWithoutProjectsInput | Prisma.TechSkillUpdateWithWhereUniqueWithoutProjectsInput[]
  updateMany?: Prisma.TechSkillUpdateManyWithWhereWithoutProjectsInput | Prisma.TechSkillUpdateManyWithWhereWithoutProjectsInput[]
  deleteMany?: Prisma.TechSkillScalarWhereInput | Prisma.TechSkillScalarWhereInput[]
}

export type TechSkillCreateWithoutContentInput = {
  id?: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
  tech: Prisma.TechCreateNestedOneWithoutSkillsInput
  projects?: Prisma.ProjectCreateNestedManyWithoutSkillsInput
}

export type TechSkillUncheckedCreateWithoutContentInput = {
  id?: string
  tech_id: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutSkillsInput
}

export type TechSkillCreateOrConnectWithoutContentInput = {
  where: Prisma.TechSkillWhereUniqueInput
  create: Prisma.XOR<Prisma.TechSkillCreateWithoutContentInput, Prisma.TechSkillUncheckedCreateWithoutContentInput>
}

export type TechSkillUpsertWithoutContentInput = {
  update: Prisma.XOR<Prisma.TechSkillUpdateWithoutContentInput, Prisma.TechSkillUncheckedUpdateWithoutContentInput>
  create: Prisma.XOR<Prisma.TechSkillCreateWithoutContentInput, Prisma.TechSkillUncheckedCreateWithoutContentInput>
  where?: Prisma.TechSkillWhereInput
}

export type TechSkillUpdateToOneWithWhereWithoutContentInput = {
  where?: Prisma.TechSkillWhereInput
  data: Prisma.XOR<Prisma.TechSkillUpdateWithoutContentInput, Prisma.TechSkillUncheckedUpdateWithoutContentInput>
}

export type TechSkillUpdateWithoutContentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tech?: Prisma.TechUpdateOneRequiredWithoutSkillsNestedInput
  projects?: Prisma.ProjectUpdateManyWithoutSkillsNestedInput
}

export type TechSkillUncheckedUpdateWithoutContentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tech_id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutSkillsNestedInput
}

export type TechSkillCreateWithoutTechInput = {
  id?: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
  content?: Prisma.TechSkillContentCreateNestedOneWithoutSkillInput
  projects?: Prisma.ProjectCreateNestedManyWithoutSkillsInput
}

export type TechSkillUncheckedCreateWithoutTechInput = {
  id?: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
  content?: Prisma.TechSkillContentUncheckedCreateNestedOneWithoutSkillInput
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutSkillsInput
}

export type TechSkillCreateOrConnectWithoutTechInput = {
  where: Prisma.TechSkillWhereUniqueInput
  create: Prisma.XOR<Prisma.TechSkillCreateWithoutTechInput, Prisma.TechSkillUncheckedCreateWithoutTechInput>
}

export type TechSkillCreateManyTechInputEnvelope = {
  data: Prisma.TechSkillCreateManyTechInput | Prisma.TechSkillCreateManyTechInput[]
  skipDuplicates?: boolean
}

export type TechSkillUpsertWithWhereUniqueWithoutTechInput = {
  where: Prisma.TechSkillWhereUniqueInput
  update: Prisma.XOR<Prisma.TechSkillUpdateWithoutTechInput, Prisma.TechSkillUncheckedUpdateWithoutTechInput>
  create: Prisma.XOR<Prisma.TechSkillCreateWithoutTechInput, Prisma.TechSkillUncheckedCreateWithoutTechInput>
}

export type TechSkillUpdateWithWhereUniqueWithoutTechInput = {
  where: Prisma.TechSkillWhereUniqueInput
  data: Prisma.XOR<Prisma.TechSkillUpdateWithoutTechInput, Prisma.TechSkillUncheckedUpdateWithoutTechInput>
}

export type TechSkillUpdateManyWithWhereWithoutTechInput = {
  where: Prisma.TechSkillScalarWhereInput
  data: Prisma.XOR<Prisma.TechSkillUpdateManyMutationInput, Prisma.TechSkillUncheckedUpdateManyWithoutTechInput>
}

export type TechSkillScalarWhereInput = {
  AND?: Prisma.TechSkillScalarWhereInput | Prisma.TechSkillScalarWhereInput[]
  OR?: Prisma.TechSkillScalarWhereInput[]
  NOT?: Prisma.TechSkillScalarWhereInput | Prisma.TechSkillScalarWhereInput[]
  id?: Prisma.StringFilter<"TechSkill"> | string
  tech_id?: Prisma.StringFilter<"TechSkill"> | string
  scope?: Prisma.EnumTechSkillScopeFilter<"TechSkill"> | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFilter<"TechSkill"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TechSkill"> | Date | string
}

export type TechSkillCreateWithoutProjectsInput = {
  id?: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
  tech: Prisma.TechCreateNestedOneWithoutSkillsInput
  content?: Prisma.TechSkillContentCreateNestedOneWithoutSkillInput
}

export type TechSkillUncheckedCreateWithoutProjectsInput = {
  id?: string
  tech_id: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
  content?: Prisma.TechSkillContentUncheckedCreateNestedOneWithoutSkillInput
}

export type TechSkillCreateOrConnectWithoutProjectsInput = {
  where: Prisma.TechSkillWhereUniqueInput
  create: Prisma.XOR<Prisma.TechSkillCreateWithoutProjectsInput, Prisma.TechSkillUncheckedCreateWithoutProjectsInput>
}

export type TechSkillUpsertWithWhereUniqueWithoutProjectsInput = {
  where: Prisma.TechSkillWhereUniqueInput
  update: Prisma.XOR<Prisma.TechSkillUpdateWithoutProjectsInput, Prisma.TechSkillUncheckedUpdateWithoutProjectsInput>
  create: Prisma.XOR<Prisma.TechSkillCreateWithoutProjectsInput, Prisma.TechSkillUncheckedCreateWithoutProjectsInput>
}

export type TechSkillUpdateWithWhereUniqueWithoutProjectsInput = {
  where: Prisma.TechSkillWhereUniqueInput
  data: Prisma.XOR<Prisma.TechSkillUpdateWithoutProjectsInput, Prisma.TechSkillUncheckedUpdateWithoutProjectsInput>
}

export type TechSkillUpdateManyWithWhereWithoutProjectsInput = {
  where: Prisma.TechSkillScalarWhereInput
  data: Prisma.XOR<Prisma.TechSkillUpdateManyMutationInput, Prisma.TechSkillUncheckedUpdateManyWithoutProjectsInput>
}

export type TechSkillCreateManyTechInput = {
  id?: string
  scope?: $Enums.TechSkillScope
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TechSkillUpdateWithoutTechInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  content?: Prisma.TechSkillContentUpdateOneWithoutSkillNestedInput
  projects?: Prisma.ProjectUpdateManyWithoutSkillsNestedInput
}

export type TechSkillUncheckedUpdateWithoutTechInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  content?: Prisma.TechSkillContentUncheckedUpdateOneWithoutSkillNestedInput
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutSkillsNestedInput
}

export type TechSkillUncheckedUpdateManyWithoutTechInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechSkillUpdateWithoutProjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tech?: Prisma.TechUpdateOneRequiredWithoutSkillsNestedInput
  content?: Prisma.TechSkillContentUpdateOneWithoutSkillNestedInput
}

export type TechSkillUncheckedUpdateWithoutProjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tech_id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  content?: Prisma.TechSkillContentUncheckedUpdateOneWithoutSkillNestedInput
}

export type TechSkillUncheckedUpdateManyWithoutProjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tech_id?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.EnumTechSkillScopeFieldUpdateOperationsInput | $Enums.TechSkillScope
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TechSkillCountOutputType
 */

export type TechSkillCountOutputType = {
  projects: number
}

export type TechSkillCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  projects?: boolean | TechSkillCountOutputTypeCountProjectsArgs
}

/**
 * TechSkillCountOutputType without action
 */
export type TechSkillCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillCountOutputType
   */
  select?: Prisma.TechSkillCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TechSkillCountOutputType without action
 */
export type TechSkillCountOutputTypeCountProjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
}


export type TechSkillSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tech_id?: boolean
  scope?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tech?: boolean | Prisma.TechDefaultArgs<ExtArgs>
  content?: boolean | Prisma.TechSkill$contentArgs<ExtArgs>
  projects?: boolean | Prisma.TechSkill$projectsArgs<ExtArgs>
  _count?: boolean | Prisma.TechSkillCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["techSkill"]>

export type TechSkillSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tech_id?: boolean
  scope?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tech?: boolean | Prisma.TechDefaultArgs<ExtArgs>
}, ExtArgs["result"]["techSkill"]>

export type TechSkillSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tech_id?: boolean
  scope?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tech?: boolean | Prisma.TechDefaultArgs<ExtArgs>
}, ExtArgs["result"]["techSkill"]>

export type TechSkillSelectScalar = {
  id?: boolean
  tech_id?: boolean
  scope?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TechSkillOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tech_id" | "scope" | "createdAt" | "updatedAt", ExtArgs["result"]["techSkill"]>
export type TechSkillInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tech?: boolean | Prisma.TechDefaultArgs<ExtArgs>
  content?: boolean | Prisma.TechSkill$contentArgs<ExtArgs>
  projects?: boolean | Prisma.TechSkill$projectsArgs<ExtArgs>
  _count?: boolean | Prisma.TechSkillCountOutputTypeDefaultArgs<ExtArgs>
}
export type TechSkillIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tech?: boolean | Prisma.TechDefaultArgs<ExtArgs>
}
export type TechSkillIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tech?: boolean | Prisma.TechDefaultArgs<ExtArgs>
}

export type $TechSkillPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TechSkill"
  objects: {
    tech: Prisma.$TechPayload<ExtArgs>
    content: Prisma.$TechSkillContentPayload<ExtArgs> | null
    projects: Prisma.$ProjectPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tech_id: string
    scope: $Enums.TechSkillScope
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["techSkill"]>
  composites: {}
}

export type TechSkillGetPayload<S extends boolean | null | undefined | TechSkillDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TechSkillPayload, S>

export type TechSkillCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TechSkillFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TechSkillCountAggregateInputType | true
  }

export interface TechSkillDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TechSkill'], meta: { name: 'TechSkill' } }
  /**
   * Find zero or one TechSkill that matches the filter.
   * @param {TechSkillFindUniqueArgs} args - Arguments to find a TechSkill
   * @example
   * // Get one TechSkill
   * const techSkill = await prisma.techSkill.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TechSkillFindUniqueArgs>(args: Prisma.SelectSubset<T, TechSkillFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TechSkill that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TechSkillFindUniqueOrThrowArgs} args - Arguments to find a TechSkill
   * @example
   * // Get one TechSkill
   * const techSkill = await prisma.techSkill.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TechSkillFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TechSkillFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TechSkill that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillFindFirstArgs} args - Arguments to find a TechSkill
   * @example
   * // Get one TechSkill
   * const techSkill = await prisma.techSkill.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TechSkillFindFirstArgs>(args?: Prisma.SelectSubset<T, TechSkillFindFirstArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TechSkill that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillFindFirstOrThrowArgs} args - Arguments to find a TechSkill
   * @example
   * // Get one TechSkill
   * const techSkill = await prisma.techSkill.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TechSkillFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TechSkillFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TechSkills that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TechSkills
   * const techSkills = await prisma.techSkill.findMany()
   * 
   * // Get first 10 TechSkills
   * const techSkills = await prisma.techSkill.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const techSkillWithIdOnly = await prisma.techSkill.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TechSkillFindManyArgs>(args?: Prisma.SelectSubset<T, TechSkillFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TechSkill.
   * @param {TechSkillCreateArgs} args - Arguments to create a TechSkill.
   * @example
   * // Create one TechSkill
   * const TechSkill = await prisma.techSkill.create({
   *   data: {
   *     // ... data to create a TechSkill
   *   }
   * })
   * 
   */
  create<T extends TechSkillCreateArgs>(args: Prisma.SelectSubset<T, TechSkillCreateArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TechSkills.
   * @param {TechSkillCreateManyArgs} args - Arguments to create many TechSkills.
   * @example
   * // Create many TechSkills
   * const techSkill = await prisma.techSkill.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TechSkillCreateManyArgs>(args?: Prisma.SelectSubset<T, TechSkillCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TechSkills and returns the data saved in the database.
   * @param {TechSkillCreateManyAndReturnArgs} args - Arguments to create many TechSkills.
   * @example
   * // Create many TechSkills
   * const techSkill = await prisma.techSkill.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TechSkills and only return the `id`
   * const techSkillWithIdOnly = await prisma.techSkill.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TechSkillCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TechSkillCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TechSkill.
   * @param {TechSkillDeleteArgs} args - Arguments to delete one TechSkill.
   * @example
   * // Delete one TechSkill
   * const TechSkill = await prisma.techSkill.delete({
   *   where: {
   *     // ... filter to delete one TechSkill
   *   }
   * })
   * 
   */
  delete<T extends TechSkillDeleteArgs>(args: Prisma.SelectSubset<T, TechSkillDeleteArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TechSkill.
   * @param {TechSkillUpdateArgs} args - Arguments to update one TechSkill.
   * @example
   * // Update one TechSkill
   * const techSkill = await prisma.techSkill.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TechSkillUpdateArgs>(args: Prisma.SelectSubset<T, TechSkillUpdateArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TechSkills.
   * @param {TechSkillDeleteManyArgs} args - Arguments to filter TechSkills to delete.
   * @example
   * // Delete a few TechSkills
   * const { count } = await prisma.techSkill.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TechSkillDeleteManyArgs>(args?: Prisma.SelectSubset<T, TechSkillDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TechSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TechSkills
   * const techSkill = await prisma.techSkill.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TechSkillUpdateManyArgs>(args: Prisma.SelectSubset<T, TechSkillUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TechSkills and returns the data updated in the database.
   * @param {TechSkillUpdateManyAndReturnArgs} args - Arguments to update many TechSkills.
   * @example
   * // Update many TechSkills
   * const techSkill = await prisma.techSkill.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TechSkills and only return the `id`
   * const techSkillWithIdOnly = await prisma.techSkill.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TechSkillUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TechSkillUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TechSkill.
   * @param {TechSkillUpsertArgs} args - Arguments to update or create a TechSkill.
   * @example
   * // Update or create a TechSkill
   * const techSkill = await prisma.techSkill.upsert({
   *   create: {
   *     // ... data to create a TechSkill
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TechSkill we want to update
   *   }
   * })
   */
  upsert<T extends TechSkillUpsertArgs>(args: Prisma.SelectSubset<T, TechSkillUpsertArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TechSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillCountArgs} args - Arguments to filter TechSkills to count.
   * @example
   * // Count the number of TechSkills
   * const count = await prisma.techSkill.count({
   *   where: {
   *     // ... the filter for the TechSkills we want to count
   *   }
   * })
  **/
  count<T extends TechSkillCountArgs>(
    args?: Prisma.Subset<T, TechSkillCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TechSkillCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TechSkill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TechSkillAggregateArgs>(args: Prisma.Subset<T, TechSkillAggregateArgs>): Prisma.PrismaPromise<GetTechSkillAggregateType<T>>

  /**
   * Group by TechSkill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TechSkillGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TechSkillGroupByArgs['orderBy'] }
      : { orderBy?: TechSkillGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TechSkillGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTechSkillGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TechSkill model
 */
readonly fields: TechSkillFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TechSkill.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TechSkillClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tech<T extends Prisma.TechDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TechDefaultArgs<ExtArgs>>): Prisma.Prisma__TechClient<runtime.Types.Result.GetResult<Prisma.$TechPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  content<T extends Prisma.TechSkill$contentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TechSkill$contentArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  projects<T extends Prisma.TechSkill$projectsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TechSkill$projectsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TechSkill model
 */
export interface TechSkillFieldRefs {
  readonly id: Prisma.FieldRef<"TechSkill", 'String'>
  readonly tech_id: Prisma.FieldRef<"TechSkill", 'String'>
  readonly scope: Prisma.FieldRef<"TechSkill", 'TechSkillScope'>
  readonly createdAt: Prisma.FieldRef<"TechSkill", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TechSkill", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TechSkill findUnique
 */
export type TechSkillFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * Filter, which TechSkill to fetch.
   */
  where: Prisma.TechSkillWhereUniqueInput
}

/**
 * TechSkill findUniqueOrThrow
 */
export type TechSkillFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * Filter, which TechSkill to fetch.
   */
  where: Prisma.TechSkillWhereUniqueInput
}

/**
 * TechSkill findFirst
 */
export type TechSkillFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * Filter, which TechSkill to fetch.
   */
  where?: Prisma.TechSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechSkills to fetch.
   */
  orderBy?: Prisma.TechSkillOrderByWithRelationInput | Prisma.TechSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TechSkills.
   */
  cursor?: Prisma.TechSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TechSkills.
   */
  distinct?: Prisma.TechSkillScalarFieldEnum | Prisma.TechSkillScalarFieldEnum[]
}

/**
 * TechSkill findFirstOrThrow
 */
export type TechSkillFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * Filter, which TechSkill to fetch.
   */
  where?: Prisma.TechSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechSkills to fetch.
   */
  orderBy?: Prisma.TechSkillOrderByWithRelationInput | Prisma.TechSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TechSkills.
   */
  cursor?: Prisma.TechSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TechSkills.
   */
  distinct?: Prisma.TechSkillScalarFieldEnum | Prisma.TechSkillScalarFieldEnum[]
}

/**
 * TechSkill findMany
 */
export type TechSkillFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * Filter, which TechSkills to fetch.
   */
  where?: Prisma.TechSkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechSkills to fetch.
   */
  orderBy?: Prisma.TechSkillOrderByWithRelationInput | Prisma.TechSkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TechSkills.
   */
  cursor?: Prisma.TechSkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TechSkills.
   */
  distinct?: Prisma.TechSkillScalarFieldEnum | Prisma.TechSkillScalarFieldEnum[]
}

/**
 * TechSkill create
 */
export type TechSkillCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * The data needed to create a TechSkill.
   */
  data: Prisma.XOR<Prisma.TechSkillCreateInput, Prisma.TechSkillUncheckedCreateInput>
}

/**
 * TechSkill createMany
 */
export type TechSkillCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TechSkills.
   */
  data: Prisma.TechSkillCreateManyInput | Prisma.TechSkillCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TechSkill createManyAndReturn
 */
export type TechSkillCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * The data used to create many TechSkills.
   */
  data: Prisma.TechSkillCreateManyInput | Prisma.TechSkillCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TechSkill update
 */
export type TechSkillUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * The data needed to update a TechSkill.
   */
  data: Prisma.XOR<Prisma.TechSkillUpdateInput, Prisma.TechSkillUncheckedUpdateInput>
  /**
   * Choose, which TechSkill to update.
   */
  where: Prisma.TechSkillWhereUniqueInput
}

/**
 * TechSkill updateMany
 */
export type TechSkillUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TechSkills.
   */
  data: Prisma.XOR<Prisma.TechSkillUpdateManyMutationInput, Prisma.TechSkillUncheckedUpdateManyInput>
  /**
   * Filter which TechSkills to update
   */
  where?: Prisma.TechSkillWhereInput
  /**
   * Limit how many TechSkills to update.
   */
  limit?: number
}

/**
 * TechSkill updateManyAndReturn
 */
export type TechSkillUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * The data used to update TechSkills.
   */
  data: Prisma.XOR<Prisma.TechSkillUpdateManyMutationInput, Prisma.TechSkillUncheckedUpdateManyInput>
  /**
   * Filter which TechSkills to update
   */
  where?: Prisma.TechSkillWhereInput
  /**
   * Limit how many TechSkills to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TechSkill upsert
 */
export type TechSkillUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * The filter to search for the TechSkill to update in case it exists.
   */
  where: Prisma.TechSkillWhereUniqueInput
  /**
   * In case the TechSkill found by the `where` argument doesn't exist, create a new TechSkill with this data.
   */
  create: Prisma.XOR<Prisma.TechSkillCreateInput, Prisma.TechSkillUncheckedCreateInput>
  /**
   * In case the TechSkill was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TechSkillUpdateInput, Prisma.TechSkillUncheckedUpdateInput>
}

/**
 * TechSkill delete
 */
export type TechSkillDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
  /**
   * Filter which TechSkill to delete.
   */
  where: Prisma.TechSkillWhereUniqueInput
}

/**
 * TechSkill deleteMany
 */
export type TechSkillDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TechSkills to delete
   */
  where?: Prisma.TechSkillWhereInput
  /**
   * Limit how many TechSkills to delete.
   */
  limit?: number
}

/**
 * TechSkill.content
 */
export type TechSkill$contentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  where?: Prisma.TechSkillContentWhereInput
}

/**
 * TechSkill.projects
 */
export type TechSkill$projectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  cursor?: Prisma.ProjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * TechSkill without action
 */
export type TechSkillDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkill
   */
  select?: Prisma.TechSkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkill
   */
  omit?: Prisma.TechSkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillInclude<ExtArgs> | null
}
