
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TechSkillContent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TechSkillContent
 * 
 */
export type TechSkillContentModel = runtime.Types.Result.DefaultSelection<Prisma.$TechSkillContentPayload>

export type AggregateTechSkillContent = {
  _count: TechSkillContentCountAggregateOutputType | null
  _min: TechSkillContentMinAggregateOutputType | null
  _max: TechSkillContentMaxAggregateOutputType | null
}

export type TechSkillContentMinAggregateOutputType = {
  id: string | null
  skill_id: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TechSkillContentMaxAggregateOutputType = {
  id: string | null
  skill_id: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TechSkillContentCountAggregateOutputType = {
  id: number
  skill_id: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TechSkillContentMinAggregateInputType = {
  id?: true
  skill_id?: true
  createdAt?: true
  updatedAt?: true
}

export type TechSkillContentMaxAggregateInputType = {
  id?: true
  skill_id?: true
  createdAt?: true
  updatedAt?: true
}

export type TechSkillContentCountAggregateInputType = {
  id?: true
  skill_id?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TechSkillContentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TechSkillContent to aggregate.
   */
  where?: Prisma.TechSkillContentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechSkillContents to fetch.
   */
  orderBy?: Prisma.TechSkillContentOrderByWithRelationInput | Prisma.TechSkillContentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TechSkillContentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechSkillContents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechSkillContents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TechSkillContents
  **/
  _count?: true | TechSkillContentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TechSkillContentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TechSkillContentMaxAggregateInputType
}

export type GetTechSkillContentAggregateType<T extends TechSkillContentAggregateArgs> = {
      [P in keyof T & keyof AggregateTechSkillContent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTechSkillContent[P]>
    : Prisma.GetScalarType<T[P], AggregateTechSkillContent[P]>
}




export type TechSkillContentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TechSkillContentWhereInput
  orderBy?: Prisma.TechSkillContentOrderByWithAggregationInput | Prisma.TechSkillContentOrderByWithAggregationInput[]
  by: Prisma.TechSkillContentScalarFieldEnum[] | Prisma.TechSkillContentScalarFieldEnum
  having?: Prisma.TechSkillContentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TechSkillContentCountAggregateInputType | true
  _min?: TechSkillContentMinAggregateInputType
  _max?: TechSkillContentMaxAggregateInputType
}

export type TechSkillContentGroupByOutputType = {
  id: string
  skill_id: string
  createdAt: Date
  updatedAt: Date
  _count: TechSkillContentCountAggregateOutputType | null
  _min: TechSkillContentMinAggregateOutputType | null
  _max: TechSkillContentMaxAggregateOutputType | null
}

type GetTechSkillContentGroupByPayload<T extends TechSkillContentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TechSkillContentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TechSkillContentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TechSkillContentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TechSkillContentGroupByOutputType[P]>
      }
    >
  >



export type TechSkillContentWhereInput = {
  AND?: Prisma.TechSkillContentWhereInput | Prisma.TechSkillContentWhereInput[]
  OR?: Prisma.TechSkillContentWhereInput[]
  NOT?: Prisma.TechSkillContentWhereInput | Prisma.TechSkillContentWhereInput[]
  id?: Prisma.StringFilter<"TechSkillContent"> | string
  skill_id?: Prisma.StringFilter<"TechSkillContent"> | string
  createdAt?: Prisma.DateTimeFilter<"TechSkillContent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TechSkillContent"> | Date | string
  skill?: Prisma.XOR<Prisma.TechSkillScalarRelationFilter, Prisma.TechSkillWhereInput>
  sections?: Prisma.TechSkillContentSectionListRelationFilter
}

export type TechSkillContentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  skill?: Prisma.TechSkillOrderByWithRelationInput
  sections?: Prisma.TechSkillContentSectionOrderByRelationAggregateInput
}

export type TechSkillContentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  skill_id?: string
  AND?: Prisma.TechSkillContentWhereInput | Prisma.TechSkillContentWhereInput[]
  OR?: Prisma.TechSkillContentWhereInput[]
  NOT?: Prisma.TechSkillContentWhereInput | Prisma.TechSkillContentWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"TechSkillContent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TechSkillContent"> | Date | string
  skill?: Prisma.XOR<Prisma.TechSkillScalarRelationFilter, Prisma.TechSkillWhereInput>
  sections?: Prisma.TechSkillContentSectionListRelationFilter
}, "id" | "skill_id">

export type TechSkillContentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TechSkillContentCountOrderByAggregateInput
  _max?: Prisma.TechSkillContentMaxOrderByAggregateInput
  _min?: Prisma.TechSkillContentMinOrderByAggregateInput
}

export type TechSkillContentScalarWhereWithAggregatesInput = {
  AND?: Prisma.TechSkillContentScalarWhereWithAggregatesInput | Prisma.TechSkillContentScalarWhereWithAggregatesInput[]
  OR?: Prisma.TechSkillContentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TechSkillContentScalarWhereWithAggregatesInput | Prisma.TechSkillContentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TechSkillContent"> | string
  skill_id?: Prisma.StringWithAggregatesFilter<"TechSkillContent"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TechSkillContent"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TechSkillContent"> | Date | string
}

export type TechSkillContentCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  skill: Prisma.TechSkillCreateNestedOneWithoutContentInput
  sections?: Prisma.TechSkillContentSectionCreateNestedManyWithoutContentInput
}

export type TechSkillContentUncheckedCreateInput = {
  id?: string
  skill_id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.TechSkillContentSectionUncheckedCreateNestedManyWithoutContentInput
}

export type TechSkillContentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  skill?: Prisma.TechSkillUpdateOneRequiredWithoutContentNestedInput
  sections?: Prisma.TechSkillContentSectionUpdateManyWithoutContentNestedInput
}

export type TechSkillContentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skill_id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.TechSkillContentSectionUncheckedUpdateManyWithoutContentNestedInput
}

export type TechSkillContentCreateManyInput = {
  id?: string
  skill_id: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TechSkillContentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechSkillContentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skill_id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechSkillContentScalarRelationFilter = {
  is?: Prisma.TechSkillContentWhereInput
  isNot?: Prisma.TechSkillContentWhereInput
}

export type TechSkillContentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechSkillContentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechSkillContentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechSkillContentNullableScalarRelationFilter = {
  is?: Prisma.TechSkillContentWhereInput | null
  isNot?: Prisma.TechSkillContentWhereInput | null
}

export type TechSkillContentCreateNestedOneWithoutSectionsInput = {
  create?: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSectionsInput, Prisma.TechSkillContentUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.TechSkillContentCreateOrConnectWithoutSectionsInput
  connect?: Prisma.TechSkillContentWhereUniqueInput
}

export type TechSkillContentUpdateOneRequiredWithoutSectionsNestedInput = {
  create?: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSectionsInput, Prisma.TechSkillContentUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.TechSkillContentCreateOrConnectWithoutSectionsInput
  upsert?: Prisma.TechSkillContentUpsertWithoutSectionsInput
  connect?: Prisma.TechSkillContentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TechSkillContentUpdateToOneWithWhereWithoutSectionsInput, Prisma.TechSkillContentUpdateWithoutSectionsInput>, Prisma.TechSkillContentUncheckedUpdateWithoutSectionsInput>
}

export type TechSkillContentCreateNestedOneWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSkillInput, Prisma.TechSkillContentUncheckedCreateWithoutSkillInput>
  connectOrCreate?: Prisma.TechSkillContentCreateOrConnectWithoutSkillInput
  connect?: Prisma.TechSkillContentWhereUniqueInput
}

export type TechSkillContentUncheckedCreateNestedOneWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSkillInput, Prisma.TechSkillContentUncheckedCreateWithoutSkillInput>
  connectOrCreate?: Prisma.TechSkillContentCreateOrConnectWithoutSkillInput
  connect?: Prisma.TechSkillContentWhereUniqueInput
}

export type TechSkillContentUpdateOneWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSkillInput, Prisma.TechSkillContentUncheckedCreateWithoutSkillInput>
  connectOrCreate?: Prisma.TechSkillContentCreateOrConnectWithoutSkillInput
  upsert?: Prisma.TechSkillContentUpsertWithoutSkillInput
  disconnect?: Prisma.TechSkillContentWhereInput | boolean
  delete?: Prisma.TechSkillContentWhereInput | boolean
  connect?: Prisma.TechSkillContentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TechSkillContentUpdateToOneWithWhereWithoutSkillInput, Prisma.TechSkillContentUpdateWithoutSkillInput>, Prisma.TechSkillContentUncheckedUpdateWithoutSkillInput>
}

export type TechSkillContentUncheckedUpdateOneWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSkillInput, Prisma.TechSkillContentUncheckedCreateWithoutSkillInput>
  connectOrCreate?: Prisma.TechSkillContentCreateOrConnectWithoutSkillInput
  upsert?: Prisma.TechSkillContentUpsertWithoutSkillInput
  disconnect?: Prisma.TechSkillContentWhereInput | boolean
  delete?: Prisma.TechSkillContentWhereInput | boolean
  connect?: Prisma.TechSkillContentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TechSkillContentUpdateToOneWithWhereWithoutSkillInput, Prisma.TechSkillContentUpdateWithoutSkillInput>, Prisma.TechSkillContentUncheckedUpdateWithoutSkillInput>
}

export type TechSkillContentCreateWithoutSectionsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  skill: Prisma.TechSkillCreateNestedOneWithoutContentInput
}

export type TechSkillContentUncheckedCreateWithoutSectionsInput = {
  id?: string
  skill_id: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TechSkillContentCreateOrConnectWithoutSectionsInput = {
  where: Prisma.TechSkillContentWhereUniqueInput
  create: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSectionsInput, Prisma.TechSkillContentUncheckedCreateWithoutSectionsInput>
}

export type TechSkillContentUpsertWithoutSectionsInput = {
  update: Prisma.XOR<Prisma.TechSkillContentUpdateWithoutSectionsInput, Prisma.TechSkillContentUncheckedUpdateWithoutSectionsInput>
  create: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSectionsInput, Prisma.TechSkillContentUncheckedCreateWithoutSectionsInput>
  where?: Prisma.TechSkillContentWhereInput
}

export type TechSkillContentUpdateToOneWithWhereWithoutSectionsInput = {
  where?: Prisma.TechSkillContentWhereInput
  data: Prisma.XOR<Prisma.TechSkillContentUpdateWithoutSectionsInput, Prisma.TechSkillContentUncheckedUpdateWithoutSectionsInput>
}

export type TechSkillContentUpdateWithoutSectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  skill?: Prisma.TechSkillUpdateOneRequiredWithoutContentNestedInput
}

export type TechSkillContentUncheckedUpdateWithoutSectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skill_id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechSkillContentCreateWithoutSkillInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.TechSkillContentSectionCreateNestedManyWithoutContentInput
}

export type TechSkillContentUncheckedCreateWithoutSkillInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.TechSkillContentSectionUncheckedCreateNestedManyWithoutContentInput
}

export type TechSkillContentCreateOrConnectWithoutSkillInput = {
  where: Prisma.TechSkillContentWhereUniqueInput
  create: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSkillInput, Prisma.TechSkillContentUncheckedCreateWithoutSkillInput>
}

export type TechSkillContentUpsertWithoutSkillInput = {
  update: Prisma.XOR<Prisma.TechSkillContentUpdateWithoutSkillInput, Prisma.TechSkillContentUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.TechSkillContentCreateWithoutSkillInput, Prisma.TechSkillContentUncheckedCreateWithoutSkillInput>
  where?: Prisma.TechSkillContentWhereInput
}

export type TechSkillContentUpdateToOneWithWhereWithoutSkillInput = {
  where?: Prisma.TechSkillContentWhereInput
  data: Prisma.XOR<Prisma.TechSkillContentUpdateWithoutSkillInput, Prisma.TechSkillContentUncheckedUpdateWithoutSkillInput>
}

export type TechSkillContentUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.TechSkillContentSectionUpdateManyWithoutContentNestedInput
}

export type TechSkillContentUncheckedUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.TechSkillContentSectionUncheckedUpdateManyWithoutContentNestedInput
}


/**
 * Count Type TechSkillContentCountOutputType
 */

export type TechSkillContentCountOutputType = {
  sections: number
}

export type TechSkillContentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sections?: boolean | TechSkillContentCountOutputTypeCountSectionsArgs
}

/**
 * TechSkillContentCountOutputType without action
 */
export type TechSkillContentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContentCountOutputType
   */
  select?: Prisma.TechSkillContentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TechSkillContentCountOutputType without action
 */
export type TechSkillContentCountOutputTypeCountSectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TechSkillContentSectionWhereInput
}


export type TechSkillContentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  skill_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  skill?: boolean | Prisma.TechSkillDefaultArgs<ExtArgs>
  sections?: boolean | Prisma.TechSkillContent$sectionsArgs<ExtArgs>
  _count?: boolean | Prisma.TechSkillContentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["techSkillContent"]>

export type TechSkillContentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  skill_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  skill?: boolean | Prisma.TechSkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["techSkillContent"]>

export type TechSkillContentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  skill_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  skill?: boolean | Prisma.TechSkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["techSkillContent"]>

export type TechSkillContentSelectScalar = {
  id?: boolean
  skill_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TechSkillContentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "skill_id" | "createdAt" | "updatedAt", ExtArgs["result"]["techSkillContent"]>
export type TechSkillContentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  skill?: boolean | Prisma.TechSkillDefaultArgs<ExtArgs>
  sections?: boolean | Prisma.TechSkillContent$sectionsArgs<ExtArgs>
  _count?: boolean | Prisma.TechSkillContentCountOutputTypeDefaultArgs<ExtArgs>
}
export type TechSkillContentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  skill?: boolean | Prisma.TechSkillDefaultArgs<ExtArgs>
}
export type TechSkillContentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  skill?: boolean | Prisma.TechSkillDefaultArgs<ExtArgs>
}

export type $TechSkillContentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TechSkillContent"
  objects: {
    skill: Prisma.$TechSkillPayload<ExtArgs>
    sections: Prisma.$TechSkillContentSectionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    skill_id: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["techSkillContent"]>
  composites: {}
}

export type TechSkillContentGetPayload<S extends boolean | null | undefined | TechSkillContentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload, S>

export type TechSkillContentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TechSkillContentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TechSkillContentCountAggregateInputType | true
  }

export interface TechSkillContentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TechSkillContent'], meta: { name: 'TechSkillContent' } }
  /**
   * Find zero or one TechSkillContent that matches the filter.
   * @param {TechSkillContentFindUniqueArgs} args - Arguments to find a TechSkillContent
   * @example
   * // Get one TechSkillContent
   * const techSkillContent = await prisma.techSkillContent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TechSkillContentFindUniqueArgs>(args: Prisma.SelectSubset<T, TechSkillContentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TechSkillContent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TechSkillContentFindUniqueOrThrowArgs} args - Arguments to find a TechSkillContent
   * @example
   * // Get one TechSkillContent
   * const techSkillContent = await prisma.techSkillContent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TechSkillContentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TechSkillContentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TechSkillContent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillContentFindFirstArgs} args - Arguments to find a TechSkillContent
   * @example
   * // Get one TechSkillContent
   * const techSkillContent = await prisma.techSkillContent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TechSkillContentFindFirstArgs>(args?: Prisma.SelectSubset<T, TechSkillContentFindFirstArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TechSkillContent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillContentFindFirstOrThrowArgs} args - Arguments to find a TechSkillContent
   * @example
   * // Get one TechSkillContent
   * const techSkillContent = await prisma.techSkillContent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TechSkillContentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TechSkillContentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TechSkillContents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillContentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TechSkillContents
   * const techSkillContents = await prisma.techSkillContent.findMany()
   * 
   * // Get first 10 TechSkillContents
   * const techSkillContents = await prisma.techSkillContent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const techSkillContentWithIdOnly = await prisma.techSkillContent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TechSkillContentFindManyArgs>(args?: Prisma.SelectSubset<T, TechSkillContentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TechSkillContent.
   * @param {TechSkillContentCreateArgs} args - Arguments to create a TechSkillContent.
   * @example
   * // Create one TechSkillContent
   * const TechSkillContent = await prisma.techSkillContent.create({
   *   data: {
   *     // ... data to create a TechSkillContent
   *   }
   * })
   * 
   */
  create<T extends TechSkillContentCreateArgs>(args: Prisma.SelectSubset<T, TechSkillContentCreateArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TechSkillContents.
   * @param {TechSkillContentCreateManyArgs} args - Arguments to create many TechSkillContents.
   * @example
   * // Create many TechSkillContents
   * const techSkillContent = await prisma.techSkillContent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TechSkillContentCreateManyArgs>(args?: Prisma.SelectSubset<T, TechSkillContentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TechSkillContents and returns the data saved in the database.
   * @param {TechSkillContentCreateManyAndReturnArgs} args - Arguments to create many TechSkillContents.
   * @example
   * // Create many TechSkillContents
   * const techSkillContent = await prisma.techSkillContent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TechSkillContents and only return the `id`
   * const techSkillContentWithIdOnly = await prisma.techSkillContent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TechSkillContentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TechSkillContentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TechSkillContent.
   * @param {TechSkillContentDeleteArgs} args - Arguments to delete one TechSkillContent.
   * @example
   * // Delete one TechSkillContent
   * const TechSkillContent = await prisma.techSkillContent.delete({
   *   where: {
   *     // ... filter to delete one TechSkillContent
   *   }
   * })
   * 
   */
  delete<T extends TechSkillContentDeleteArgs>(args: Prisma.SelectSubset<T, TechSkillContentDeleteArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TechSkillContent.
   * @param {TechSkillContentUpdateArgs} args - Arguments to update one TechSkillContent.
   * @example
   * // Update one TechSkillContent
   * const techSkillContent = await prisma.techSkillContent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TechSkillContentUpdateArgs>(args: Prisma.SelectSubset<T, TechSkillContentUpdateArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TechSkillContents.
   * @param {TechSkillContentDeleteManyArgs} args - Arguments to filter TechSkillContents to delete.
   * @example
   * // Delete a few TechSkillContents
   * const { count } = await prisma.techSkillContent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TechSkillContentDeleteManyArgs>(args?: Prisma.SelectSubset<T, TechSkillContentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TechSkillContents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillContentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TechSkillContents
   * const techSkillContent = await prisma.techSkillContent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TechSkillContentUpdateManyArgs>(args: Prisma.SelectSubset<T, TechSkillContentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TechSkillContents and returns the data updated in the database.
   * @param {TechSkillContentUpdateManyAndReturnArgs} args - Arguments to update many TechSkillContents.
   * @example
   * // Update many TechSkillContents
   * const techSkillContent = await prisma.techSkillContent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TechSkillContents and only return the `id`
   * const techSkillContentWithIdOnly = await prisma.techSkillContent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TechSkillContentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TechSkillContentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TechSkillContent.
   * @param {TechSkillContentUpsertArgs} args - Arguments to update or create a TechSkillContent.
   * @example
   * // Update or create a TechSkillContent
   * const techSkillContent = await prisma.techSkillContent.upsert({
   *   create: {
   *     // ... data to create a TechSkillContent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TechSkillContent we want to update
   *   }
   * })
   */
  upsert<T extends TechSkillContentUpsertArgs>(args: Prisma.SelectSubset<T, TechSkillContentUpsertArgs<ExtArgs>>): Prisma.Prisma__TechSkillContentClient<runtime.Types.Result.GetResult<Prisma.$TechSkillContentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TechSkillContents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillContentCountArgs} args - Arguments to filter TechSkillContents to count.
   * @example
   * // Count the number of TechSkillContents
   * const count = await prisma.techSkillContent.count({
   *   where: {
   *     // ... the filter for the TechSkillContents we want to count
   *   }
   * })
  **/
  count<T extends TechSkillContentCountArgs>(
    args?: Prisma.Subset<T, TechSkillContentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TechSkillContentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TechSkillContent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillContentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TechSkillContentAggregateArgs>(args: Prisma.Subset<T, TechSkillContentAggregateArgs>): Prisma.PrismaPromise<GetTechSkillContentAggregateType<T>>

  /**
   * Group by TechSkillContent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechSkillContentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TechSkillContentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TechSkillContentGroupByArgs['orderBy'] }
      : { orderBy?: TechSkillContentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TechSkillContentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTechSkillContentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TechSkillContent model
 */
readonly fields: TechSkillContentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TechSkillContent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TechSkillContentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  skill<T extends Prisma.TechSkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TechSkillDefaultArgs<ExtArgs>>): Prisma.Prisma__TechSkillClient<runtime.Types.Result.GetResult<Prisma.$TechSkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sections<T extends Prisma.TechSkillContent$sectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TechSkillContent$sectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechSkillContentSectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TechSkillContent model
 */
export interface TechSkillContentFieldRefs {
  readonly id: Prisma.FieldRef<"TechSkillContent", 'String'>
  readonly skill_id: Prisma.FieldRef<"TechSkillContent", 'String'>
  readonly createdAt: Prisma.FieldRef<"TechSkillContent", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TechSkillContent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TechSkillContent findUnique
 */
export type TechSkillContentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * Filter, which TechSkillContent to fetch.
   */
  where: Prisma.TechSkillContentWhereUniqueInput
}

/**
 * TechSkillContent findUniqueOrThrow
 */
export type TechSkillContentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * Filter, which TechSkillContent to fetch.
   */
  where: Prisma.TechSkillContentWhereUniqueInput
}

/**
 * TechSkillContent findFirst
 */
export type TechSkillContentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * Filter, which TechSkillContent to fetch.
   */
  where?: Prisma.TechSkillContentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechSkillContents to fetch.
   */
  orderBy?: Prisma.TechSkillContentOrderByWithRelationInput | Prisma.TechSkillContentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TechSkillContents.
   */
  cursor?: Prisma.TechSkillContentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechSkillContents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechSkillContents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TechSkillContents.
   */
  distinct?: Prisma.TechSkillContentScalarFieldEnum | Prisma.TechSkillContentScalarFieldEnum[]
}

/**
 * TechSkillContent findFirstOrThrow
 */
export type TechSkillContentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * Filter, which TechSkillContent to fetch.
   */
  where?: Prisma.TechSkillContentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechSkillContents to fetch.
   */
  orderBy?: Prisma.TechSkillContentOrderByWithRelationInput | Prisma.TechSkillContentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TechSkillContents.
   */
  cursor?: Prisma.TechSkillContentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechSkillContents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechSkillContents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TechSkillContents.
   */
  distinct?: Prisma.TechSkillContentScalarFieldEnum | Prisma.TechSkillContentScalarFieldEnum[]
}

/**
 * TechSkillContent findMany
 */
export type TechSkillContentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * Filter, which TechSkillContents to fetch.
   */
  where?: Prisma.TechSkillContentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechSkillContents to fetch.
   */
  orderBy?: Prisma.TechSkillContentOrderByWithRelationInput | Prisma.TechSkillContentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TechSkillContents.
   */
  cursor?: Prisma.TechSkillContentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechSkillContents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechSkillContents.
   */
  skip?: number
  distinct?: Prisma.TechSkillContentScalarFieldEnum | Prisma.TechSkillContentScalarFieldEnum[]
}

/**
 * TechSkillContent create
 */
export type TechSkillContentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * The data needed to create a TechSkillContent.
   */
  data: Prisma.XOR<Prisma.TechSkillContentCreateInput, Prisma.TechSkillContentUncheckedCreateInput>
}

/**
 * TechSkillContent createMany
 */
export type TechSkillContentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TechSkillContents.
   */
  data: Prisma.TechSkillContentCreateManyInput | Prisma.TechSkillContentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TechSkillContent createManyAndReturn
 */
export type TechSkillContentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * The data used to create many TechSkillContents.
   */
  data: Prisma.TechSkillContentCreateManyInput | Prisma.TechSkillContentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TechSkillContent update
 */
export type TechSkillContentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * The data needed to update a TechSkillContent.
   */
  data: Prisma.XOR<Prisma.TechSkillContentUpdateInput, Prisma.TechSkillContentUncheckedUpdateInput>
  /**
   * Choose, which TechSkillContent to update.
   */
  where: Prisma.TechSkillContentWhereUniqueInput
}

/**
 * TechSkillContent updateMany
 */
export type TechSkillContentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TechSkillContents.
   */
  data: Prisma.XOR<Prisma.TechSkillContentUpdateManyMutationInput, Prisma.TechSkillContentUncheckedUpdateManyInput>
  /**
   * Filter which TechSkillContents to update
   */
  where?: Prisma.TechSkillContentWhereInput
  /**
   * Limit how many TechSkillContents to update.
   */
  limit?: number
}

/**
 * TechSkillContent updateManyAndReturn
 */
export type TechSkillContentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * The data used to update TechSkillContents.
   */
  data: Prisma.XOR<Prisma.TechSkillContentUpdateManyMutationInput, Prisma.TechSkillContentUncheckedUpdateManyInput>
  /**
   * Filter which TechSkillContents to update
   */
  where?: Prisma.TechSkillContentWhereInput
  /**
   * Limit how many TechSkillContents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TechSkillContent upsert
 */
export type TechSkillContentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * The filter to search for the TechSkillContent to update in case it exists.
   */
  where: Prisma.TechSkillContentWhereUniqueInput
  /**
   * In case the TechSkillContent found by the `where` argument doesn't exist, create a new TechSkillContent with this data.
   */
  create: Prisma.XOR<Prisma.TechSkillContentCreateInput, Prisma.TechSkillContentUncheckedCreateInput>
  /**
   * In case the TechSkillContent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TechSkillContentUpdateInput, Prisma.TechSkillContentUncheckedUpdateInput>
}

/**
 * TechSkillContent delete
 */
export type TechSkillContentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
  /**
   * Filter which TechSkillContent to delete.
   */
  where: Prisma.TechSkillContentWhereUniqueInput
}

/**
 * TechSkillContent deleteMany
 */
export type TechSkillContentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TechSkillContents to delete
   */
  where?: Prisma.TechSkillContentWhereInput
  /**
   * Limit how many TechSkillContents to delete.
   */
  limit?: number
}

/**
 * TechSkillContent.sections
 */
export type TechSkillContent$sectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContentSection
   */
  select?: Prisma.TechSkillContentSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContentSection
   */
  omit?: Prisma.TechSkillContentSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentSectionInclude<ExtArgs> | null
  where?: Prisma.TechSkillContentSectionWhereInput
  orderBy?: Prisma.TechSkillContentSectionOrderByWithRelationInput | Prisma.TechSkillContentSectionOrderByWithRelationInput[]
  cursor?: Prisma.TechSkillContentSectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TechSkillContentSectionScalarFieldEnum | Prisma.TechSkillContentSectionScalarFieldEnum[]
}

/**
 * TechSkillContent without action
 */
export type TechSkillContentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechSkillContent
   */
  select?: Prisma.TechSkillContentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechSkillContent
   */
  omit?: Prisma.TechSkillContentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechSkillContentInclude<ExtArgs> | null
}
