
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TechSkillScope = {
  GENERAL: 'GENERAL',
  PROJECT: 'PROJECT'
} as const

export type TechSkillScope = (typeof TechSkillScope)[keyof typeof TechSkillScope]


export const ProjectType = {
  FEATURED: 'FEATURED',
  DISPLAYED: 'DISPLAYED',
  HIDDEN: 'HIDDEN'
} as const

export type ProjectType = (typeof ProjectType)[keyof typeof ProjectType]


export const TechCategory = {
  FRONTEND: 'FRONTEND',
  BACKEND: 'BACKEND',
  OTHER: 'OTHER'
} as const

export type TechCategory = (typeof TechCategory)[keyof typeof TechCategory]


export const Unit = {
  GRAM: 'GRAM',
  STALK: 'STALK',
  UNIT: 'UNIT',
  HEAD: 'HEAD'
} as const

export type Unit = (typeof Unit)[keyof typeof Unit]
